### ISSUE TITLE
native tls support

### ISSUE THREAD

**Issue by GopherJ** [bytebeamio/rumqtt#101]
rustls still has some limitations, some old certificates are not supported.

Do you have a plan to add native-tls as a feature?

**Comment by tekjar** [comment]
@GopherJ I don't have any plans to add native-tls  ATM. I'm ok with new features when this project has more maintainers. I feel more code is a burden on me at this point.

**Comment by GopherJ** [comment]
@tekjar Hi, I would definitely be happy to contribute. I'll start to read your code and don't hesitate to assign tasks to me. I'll try to see how to add native-tls first.

**Comment by tekjar** [comment]
@GopherJ That would be great. Thanks!! :)

**Comment by tekjar** [comment]
I'm closing this as this isn't a priority at the moment. But pull requests are obviously welcome :)
