### ISSUE TITLE
max_packet_size from MqttOptions is unused

### ISSUE THREAD

**Issue by jplatte** [bytebeamio/rumqtt#108]
`Network::new` just hardcodes the max packet size to 1024, making `rumqttc` unusable for many use cases.

**Comment by tekjar** [comment]
Thanks!! I'll fix this this week

**Comment by jplatte** [comment]
Fix in the maxsize branch works, can you merge it into master?

**Comment by tekjar** [comment]
I'll merge it today

**Comment by jplatte** [comment]
Fixed by #114.
