### ISSUE TITLE
TLS works on OSX, fails on yocto linux

### ISSUE THREAD

**Issue by denizs** [bytebeamio/rumqtt#118]
# Expected behaviour
Connecting to an MQTT broker via TLS works on all platforms

# Actual behaviour
Succeeds on Darwin:
```bash
2020-08-20 10:01:56.213 - DEBUG - Received a message from MQTT broker: (Some(Connected), None)
```
Fails on Yocto linux:
```bash
2020-08-20 11:53:00.441 - ERROR - Connection error: Network(Io(Custom { kind: InvalidData, error: WebPKIError(UnknownIssuer) }))
```

It's the exact same code, where we read the CA if present:
```rust
let ca = fs::read(&mqttpub_config.ca_pem_path).await.map_err(|e| {
    let error = format!(
        "Could not read CA file \"{}\": {}",
        mqttpub_config.ca_pem_path, e
    );
    io::Error::new(io::ErrorKind::Other, error)
})?;
mqttoptions.set_ca(ca);
```

# Further investigation 
I observed that on both platforms, `rustls` is using different TLSv1.3 encrypted extensions:

```bash
# OSX
2020-08-20 10:01:56.123 - DEBUG - rustls::client::tls13 - TLS1.3 encrypted extensions: []
```

```bash
# Linux / yocto
2020-08-20 10:01:56.123 - DEBUG - rustls::client::tls13 - TLS1.3 encrypted extensions: [ServerNameAck]
```

**Comment by tekjar** [comment]
I don't see any relation between the extensions and `WebPKIError(UnknownIssuer)`. Are you sure you are using the correct CA file on yocto?

**Comment by denizs** [comment]
Me neither, but tbh I‘m not at all Familie with all the details of TLS. I even copied the CA from the doctor device to make sure.
Another notable difference is that the device is running on a ROFS, but I expected that in case the set_ca call or the underlying ClientConfig.root_store.add_pem would use something alike, I‘d get some sort of a runtime error.

Von meinem iPhone gesendet

Am 20.08.2020 um 17:49 schrieb Ravi Teja <notifications@github.com>:

﻿

I don't see any relation between the extensions and WebPKIError(UnknownIssuer). Are you sure you are using the correct CA file on yocto?

**Comment by denizs** [comment]
This is definitely not an issue with `rumqttc`, so closing. To whom it may concern:
The problem seems to be that the server cert from `rustls::client' is receiving differs on both machines. The one on my machine is valid and includes the hostname, whereas the one on the yocto device doesn't.

I've diffed both `ClientHello` and `ServerHello` messages and besides the random section, the only difference is the cipher being used.
