### ISSUE TITLE
Subscribing and publishing directly to Broker

### ISSUE THREAD

**Issue by rushidesai** [bytebeamio/rumqtt#119]
Not clear whether this is possible. But it will be cool to give users of rumqttd the ability to directly subscribe and publish to Broker. e.g. see this [Javascript library](https://github.com/moscajs/aedes/blob/master/docs/Aedes.md#aedessubscribe-topic-deliverfunc-callback)

**Comment by tekjar** [comment]
@rushidesai I don't understand what the documentation is trying to say. Is this about the ability to publish and subscriber when you embed the broker?

**Comment by tekjar** [comment]
Current master has embedding support in the broker. Still early though. Feel free to open a new issue in case there is a problem

https://github.com/bytebeamio/rumqtt/blob/master/rumqttd/examples/broker.rs
