### ISSUE TITLE
LastWill message is String instead of Vec<u8>

### ISSUE THREAD

**Issue by tfishr** [bytebeamio/rumqtt#122]
I am creating a Sparkplug™ B client as my first big Rust project. The Sparkplug™ B specification requires `LastWill` message be a binary Protocol Buffers type. But the type on rumqttc `LastWill` is `String`.

Is there any other way to create the connection using a `Vec<u8>` or `Bytes` or something of that nature as the data type for the `message` field of `LastWill` struct?

**Comment by tekjar** [comment]
Good catch. That should've been some form of array of bytes. Will be fixed soon. Thanks!! :)

**Comment by qwandor-google** [comment]
I'd also like this to be fixed, if nobody else is looking at it already I can send a patch.

**Comment by tekjar** [comment]
@qwandor-google Go for it :)
