### ISSUE TITLE
rustfmt everything

### ISSUE THREAD

**Issue by qwandor-google** [bytebeamio/rumqtt#125]
My editor is set to automatically run rustfmt on save. However, the rumqtt code hasn't been run through rustfmt before, so this always generates a bunch of spurious changes which I have to revert. How would people feel about running rustfmt over everything, to avoid this problem in future?

Alternatively, it might be possible to add a rustfmt.toml which disables it.

**Comment by tekjar** [comment]
Some code looks very weird with rustfmt. But I think it's ok to pay that cost for standardization. I'll do it in a few days once my wip branch is merged to master.
