### ISSUE TITLE
Implement Unsubscribe and other missing requests

### ISSUE THREAD

**Issue by jplatte** [bytebeamio/rumqtt#147]
[`handle_outgoing_packet`] is still missing at least one branch for `Unsubscribe`, but there's probably more. Are there plans to fix this soon(-ish)?

[`handle_outgoing_packet`]: https://github.com/bytebeamio/rumqtt/blob/778f0055716f3473e0f104cabba2010d731272db/rumqttc/src/state.rs#L124-L131

**Comment by tekjar** [comment]
Implemented unsubscribe and disconnect in `unsubscribe` branch. Can you verify?

**Comment by jplatte** [comment]
I don't really have the means to quickly test locally, but I had a look at your code and it seems to be the exact equivalent of what subscribe does and only exposes functionality that's already available at a lower level. I'd be happy to see it merged as-is.

**Comment by tekjar** [comment]
Ok I've tested these locally and the are fine. I'll merge this along with 0.1 release
