### ISSUE TITLE
Please add a LICENSE file to the repository root

### ISSUE THREAD

**Issue by jplatte** [bytebeamio/rumqtt#150]
The individual crates' `Cargo.toml`s declare the license to be Apache 2.0, but it would be good to make the license a bit clearer through a `LICENSE` file and maybe a note in the `README.md`.

**Comment by bfrog** [comment]
I concur, would love to use this crate in the future for a wide variety of things, a lack of a LICENSE file puts that off

**Comment by jplatte** [comment]
@tekjar ping

**Comment by tekjar** [comment]
@jplatte Can you send a PR with apache 2.0 license?

**Comment by TotalKrill** [comment]
https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/adding-a-license-to-a-repository

I think this is best done by the repository owner

**Comment by jplatte** [comment]
How would it matter who creates the file? I'll open a PR.

**Comment by TotalKrill** [comment]
I just did, realised i could do it as well.

**Comment by jplatte** [comment]
You did? I don't see where.

**Comment by TotalKrill** [comment]
We overlapped, i removed mine now

**Comment by jplatte** [comment]
Wait, you removed it? Oh :D

**Comment by TotalKrill** [comment]
Github issues is not the best live chat tool haha

**Comment by jplatte** [comment]
For some reason I thought you had merge rights and merged your own one right away.
