### ISSUE TITLE
Using rustls prohibits client connection to IP address with self-signed cert

### ISSUE THREAD

**Issue by detly** [bytebeamio/rumqtt#163]
I am currently prototyping an MQTT system and just using unnamed servers with bare IP addresses and a self-signed certificate. Not strictly secure, but it means I can make some minor changes to use the real thing if and when I want to.

Unfortunately [rustls does not permit this](https://github.com/ctz/rustls/issues/184). When I run your async example code I get:

```text
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Network(DNSName(InvalidDNSNameError))', src/main.rs:38:28
```

That line is:

```rust
client.subscribe("/testtopic", QoS::ExactlyOnce).await.unwrap();
```

I realise this is an issue with rustls, not rumqttc, but I'm opening it here for a couple of reasons:

1. I noticed there were some other issues suggesting allowing different SSL backends.
2. Really just an FYI for anyone else using this crate and encountering this error.

**Comment by tekjar** [comment]
Work around is to create a mapping in `/etc/hosts` if you are on linux

**Comment by tekjar** [comment]
@detly I think this should be an FAQ. Can you add FAQ to readme and close this?

**Comment by detly** [comment]
Sorry, where is the FAQ?
