### ISSUE TITLE
rumqttc only receives first 120 retained messages when subscribing to a topic on a Mosquitto broker

### ISSUE THREAD

**Issue by qwandor-google** [bytebeamio/rumqtt#170]
Using Mosquitto `1.5.7-1+deb10u1` from the Debian package, and the example from #169 to test, when I subscribe to a topic filter which matches many retained messages, I consistently only receive the first 120 messages. Any further messages never arrive. If I subscribe with `mosquitto_sub` on the command line, I get all the expected messages.

This may be related to PUBACK packets somehow. The Mosquitto `max_inflight_messages` config option defaults to 20. If I change it to some other value _n_, I consistently get the first _n + 100_ messages I expect.

**Comment by qwandor-google** [comment]
https://github.com/novastone-media/MQTT-Client-Framework/issues/130 looks like a similar bug in a different MQTT client, with the same symptoms, caused by something to do with not sending PUBACKs properly.

**Comment by qwandor-google** [comment]
Aha, and the 100 comes from the Mosquitto `max_queued_messages` option. So we are receiving only the first `max_queued_messages + max_inflight_messages` retained messages. I'm not clear on whether the bug here is in Mosquitto, rumqttc or both. But the fact that `mosquitto_sub` manages to get them all suggests that rumqttc is doing something different, at least.

**Comment by tekjar** [comment]
I'll debug this tomorrow

**Comment by qwandor-google** [comment]
It turns out I see the same behaviour from `mosquitto_sub` if I pass `-q 1`, so I think this might actually be a Mosquitto bug rather than a rumqttc bug.

**Comment by qwandor-google** [comment]
It looks like this is caused by https://github.com/eclipse/mosquitto/issues/1517. I'll close this issue as I don't think the problem is with rumqttc after all.
