### ISSUE TITLE
Extracting Payload

### ISSUE THREAD

**Issue by PRADEEPKJ** [bytebeamio/rumqtt#172]
Hi,
I looked into the rumqttc examples, the subscriber code directly prints the whole packet, including meta data. Is there any API to extract just the payload?

Thanks,
Pradeep

**Comment by tekjar** [comment]
If you mean you want to access payload field of `Publish` message

https://docs.rs/rumqttc/0.1.2/rumqttc/struct.Publish.html#structfield.payload

**Comment by PRADEEPKJ** [comment]
I meant in subscriber, in below code, if I print notification, whole packet get printed. I just need the payload part of the packet. I can parse the string and extract it, but is there any simple way to do that.

// Iterate to poll the eventloop for connection progress
    for (i, notification) in connection.iter().enumerate() {
        println!("Notification = {:?}", notification);
    }

**Comment by tekjar** [comment]
```rust
if let Event::Incoming(Incoming::Publish(publish)) = notification {
    println!("Payload = {:?}", publish.payload);
}
```

**Comment by PRADEEPKJ** [comment]
For some reason that dint work directly, but below one worked. 
 
if let Ok(Event::Incoming(Incoming::Publish(publish))) = notification {
            println!("Payload = {:?}", publish.payload);

**Comment by tekjar** [comment]
Yeah. I missed extracting `Result`. This is standard rust's pattern matching.
