### ISSUE TITLE
Problem with Pub-sub in different processes

### ISSUE THREAD

**Issue by PRADEEPKJ** [bytebeamio/rumqtt#173]
I have created a publisher and a subscriber, both run as different process based on the CLI option. Now when I start the publisher, it seems running, but does not see any entries connecting to the broker in the mqttborker logs. (I use mosquitto). Find the code below. How can I fix the issue?. The subscriber fails to receive any messages. 
Find the code below
      
           //publisher
          match cmode == "publish" {
                true => {
                let mut mqtt_options = MqttOptions::new("pub-1", "localhost", 1883);
                mqtt_options.set_keep_alive(5);
                let (mut client,  _connection) = Client::new(mqtt_options, 10);
  
                     //Sends 5 messages
                     for i in 0..5 {
                        let payload = format!("{} {}",msg, i);
                        println!("Published Message: {}",payload);
                        let sleep_time = Duration::from_secs(5);
                        thread::sleep(sleep_time);
                        client.publish(mtopic.clone(),  QoS::AtLeastOnce, false, payload).unwrap();
                     }
  
                     thread::sleep(Duration::from_secs(5));
                //     done_tx.send(true).unwrap();
  
                },
                _=> println!(""),
          }
  
          //subscriber
          match cmode == "subscribe" {
              true => {
               let mut mqtt_options = MqttOptions::new("sub-1","localhost", 1883);
               mqtt_options.set_keep_alive(5);
                let (mut client, mut connection) = Client::new(mqtt_options, 10);
  
                  client.subscribe(mtopic.clone(), QoS::AtLeastOnce).unwrap();
                  println!("Subscriber mode---------------------------");
              for (i, notification) in connection.iter().enumerate() {
                  if i == 10 {
                      break;
                  }
  
                  println!("Received Notification = {:?}", notification);
                  if let Ok(Event::Incoming(Incoming::Publish(publish))) = notification {
                      println!("Payload = {:?}", publish.payload);
                  }
             }
            println!("Iterator 1 done!!");
             for notification in connection.iter() {
                    println!("Received Notification = {:?}", notification);
                      if let Ok(Event::Incoming(Incoming::Publish(publish))) = notification {
                          println!("Payload = {:?}", publish.payload);
                      }
                  }
               }

**Comment by tekjar** [comment]
Is it a publisher problem or subscriber problem?

**Comment by PRADEEPKJ** [comment]
Basically both, to start with say publisher, as I do not see any entries in the logs. I feel the connection is not going through correctly. Next is if say, without entry if still publishing I do not see messages in the subscriber side. So, it could be even subscriber problem as well. Just receive below messages on subscriber side 
Received Notification = Ok(Incoming(PingResp))
Received Notification = Ok(Outgoing(PingReq))
Received Notification = Ok(Incoming(PingResp))
Received Notification = Ok(Outgoing(PingReq))
Iterator 1 done!!                                                [**Looks like publisher s publishing successfully]**
Received Notification = Ok(Outgoing(PingReq))
Received Notification = Ok(Incoming(PingResp))
Received Notification = Ok(Outgoing(PingReq))
Received Notification = Ok(Incoming(PingResp))
Received Notification = Ok(Outgoing(PingReq)

**Comment by tekjar** [comment]
Ok. I suggest you try smaller publish and subscribe examples separately and pinpoint the problem. I can debug from there

**Comment by PRADEEPKJ** [comment]
Sure, I will try.

**Comment by PRADEEPKJ** [comment]
It works, the issue is we need to extract the notifications in the publisher, somehow it acts as a Ack, till then the sub will not receive the messages. The below block is very important, without this it fails to work.

//This is to synchronize the pub and sub  
     for (i,  _notification) in connection.iter().enumerate() {
            if i == 10 {
                   break;
            }
     }

But have one more issue, when I send 4 messages only 3 are received. When I run the publisher again, the sub will receive the older, buffered message. Any reason why its happening?

**Comment by tekjar** [comment]
`Eventloop` and `Client` communicates via a channel. 10 is buffer size of the channel.


> But have one more issue, when I send 4 messages only 3 are received. When I run the publisher again, the sub will receive the older, buffered message. Any reason why its happening?

No idea. Again I suggest creating a well formatted, minimal reproducible example that I can act on :). Closing this. Please open a new issue.

**Comment by PRADEEPKJ** [comment]
Sure, one last question on the same, is there anyway to keep publishing without waiting for the acks or without iterating over the notifications on the channel

**Comment by skreborn** [comment]
@PRADEEPKJ Iterating over the notifications is a must as far as I can tell. In fact, it's [documented so](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/README.md#important-notes).

> Looping on `connection.iter()/eventloop.poll()` is necessary to run the event loop and make progress. It yields incoming and outgoing activity notifications which allows customization as you see fit.

**Comment by PRADEEPKJ** [comment]
OK, thanks. In that case, when its idle, no messages to publish, it will utilize some cpu right?

**Comment by tekjar** [comment]
@PRADEEPKJ No it won't use any cpu. It'll just block
