### ISSUE TITLE
De/Serialization feature

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytebeamio/rumqtt#178]
Hi,

Does rumqttc provides any inbuilt de/serearilization apis?

**Comment by tekjar** [comment]
`mqtt4bytes` provide these

**Comment by PRADEEPKJ** [comment]
ok, thanks, one more question, how can I use these tests that are present inside the rumqttc? also are there any inbuilt tests for rumqttc?

**Comment by tekjar** [comment]
> also are there any inbuilt tests for rumqttc?

rumqttc has a bunch of unit and integrations tests


> how can I use these tests that are present inside the rumqttc?

Sorry. I don't understand the question. What do you mean by **using** tests?

**Comment by PRADEEPKJ** [comment]
Sorry. I don't understand the question. What do you mean by using tests?

 I mean, to run these tests I need to run at root directory, but if I just want to test the rumqttc libs, how can I run. Tried many options dint work. Could you please help me?.

**Comment by tekjar** [comment]
Go to rumqttc directory and run `cargo test`

**Comment by PRADEEPKJ** [comment]
Hmm, thanks!. One last question. Have you done any run memory foot print measurement for the client?, I did it looks in MBs and its difficult to use in memory constrained devices. Any help would be greatly helpful

**Comment by tekjar** [comment]
Most of the memory usage depends on number of messages in flight. Can you check how much memory client uses before handling any data?

**Comment by PRADEEPKJ** [comment]
With default built rumqttc publisher 138972KB (This uses glibc). With musl-libc its 3668kb. Still both are high for the memory constrained devices.
