### ISSUE TITLE
Add topic + payload extraction to example

### ISSUE THREAD

**Issue by vmasdani** [bytebeamio/rumqtt#180]
Would it be OK to add the topic and payload extraction to the rumqttc subscribe example? I think it would help a lot of people who want to use this lib, here in https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/examples/asyncpubsub.rs

Just a simple result extraction would be nice like what you did in #172 
```rust
if let Event::Incoming(Incoming::Publish(p)) = notification {
    println!("Topic: {:?}, Payload: {:?}", p.topic, p.payload);
}
```

**Comment by tekjar** [comment]
Sure! Please send a PR

**Comment by vmasdani** [comment]
Done, I've added #181 👍
