### ISSUE TITLE
Allow "oneshot" publishing

### ISSUE THREAD

**Issue by icewind1991** [bytebeamio/rumqtt#186]
I would like to publish a single message from my program and exit once the message is send, but since you need to `poll` the event loop there doesn't seem to be a clean way to do this as there doesn't seem to be a way to detect when the client is done with the publish.

I've worked around it by running the `poll` loop in a timeout but that's far from optimal.

(The library is very nice otherwise, great job devs)

**Comment by TotalKrill** [comment]
in the poll loop, can you not just wait for the Event::Outgoing(Outgoing::Publish(u16)) event?

or as an alternative, just send a disconnect directly after your publish and wait for the eventloop to start handling that.

**Comment by icewind1991** [comment]
Sending and listening for a disconnect works, thanks for the help.

Would still be nice to have a convenience method for this though, I'm probably not the only one with this use case.

**Comment by vmasdani** [comment]
Hello. I came across the need for this too.
Basically I'm creating an IoT system in my house which can turn on and off solenoid valves by invoking a `POST` http request to the `/water` actix web endpoint.  
Basically when I hit the `/water` endpoint, I want to send an MQTT request to a microcontroller with the appropriate ID which processes the request. Say, `{ "water_on": true }` with topic `4/water`. I ended up using the disconnect method mentioned by @TotalKrill 

I ended up with something like this.
```rust
#[post("/water")]
pub async fn water(water_data: web::Json<WaterBody>) -> impl Responder {
    let uuid_new = uuid::Uuid::new_v4().to_string();

    let mut mqttoptions = MqttOptions::new(uuid_new.as_str(), "localhost", 1883);
    mqttoptions.set_keep_alive(5);

    let (mut client, mut eventloop) = AsyncClient::new(mqttoptions, 10);
    client
        .subscribe(format!("{}/water", water_data.id), QoS::AtMostOnce)
        .await;

    client
        .publish(
            format!("{}/water", water_data.id),
            QoS::AtLeastOnce,
            false,
            serde_json::to_string(&WaterSendBody {
                water_on: water_data.water_on,
            })
            .unwrap()
            .as_bytes(),
        )
        .await;

    client.disconnect().await;

    loop {
        match eventloop.poll().await {
            Ok(Event::Outgoing(rumqttc::Outgoing::Disconnect)) => {
                println!("Disconnect reached!");
                break;
            }
            _ => {
                println!("Irrelevant");
            }
        }
    }

    println!("Send OK");

    HttpResponse::Ok().body("OK")
}
```

But it would be nice if we can just do something like:

```rust
#[post("/water")]
pub async fn water(water_data: web::Json<WaterBody>) -> impl Responder {
    let uuid_new = uuid::Uuid::new_v4().to_string();

    let mut mqttoptions = rumqttc::oneshot_publish(
        uuid_new.as_str(),
        "localhost",
        1883,
        QoS::AtLeastOnce,
        false,
        serde_json::to_string(&WaterSendBody {
            water_on: water_data.water_on,
        })
        .unwrap()
        .as_bytes(),
    );

    HttpResponse::Ok().body("OK")
}
```

If anyone's curious about what I'm working on, I'm using it in my project [here](https://github.com/vmasdani/twiot-gateway/blob/d2fc26acd91926d98240ee946ac2a9a90ed77746/src/handler.rs#L558)

**Comment by TotalKrill** [comment]
You could just create your own function for that. To be honest it doesn't really seems like it would warrant a part of the library. But that might be just me

**Comment by vmasdani** [comment]
> You could just create your own function for that. To be honest it doesn't really seems like it would warrant a part of the library. But that might be just me

I agree that we could just create a user defined function as it's not that complicated. I guess I'm just too used to paho's oneshot publish API, but I can certainly live without it--This isn't paho after all, rumqtt/rumqttc has heavy async abstraction.
I think the most hassle-free approach is just create an example for this oneshot publish thingy. I'll send a PR creating an example named `asyncpub_oneshot.rs` or something just for documentation.

**Comment by dwhiteddsoft** [comment]
As a new user of the library maybe I simply need to understand better the designer's philosophy in creating this library. It seems a little strange to me that I have to poll to get any publish to work. Is there a doc somewhere that explains the "why" of that? Remember, I am a bit new to Rust as well. The only thing I can suppose is that there is some underlying intrinsic being used that "the wheel doesnt spin" until polling starts.

**Comment by tekjar** [comment]
Network related code is usually full of buffers. `client -> eventloop`, `eventloop -> linux network stack`, several routers in between, `network stack -> broker userspace`. 

Rumqtt's `Outgoing` doesn't give any guarantee that the packet has reached the broker. It can only be determined by incoming ack. 

Performance being a primary goal, and outgoing and incoming events being independent with 2 different handles by design (like a channel), oneshot/synchronous publishes are not a primary goal of this library.

Please feel free to reopen if this needs further discussion
