### ISSUE TITLE
Is this a rewrite of rumqtt?

### ISSUE THREAD

**Issue by Progdrasil** [bytebeamio/rumqtt#19]
We started using Rumqtt at work last year, and now I see that is has been archived and ownership is transferred here. Since this is in alpha state, is it a rewrite?

**Comment by tekjar** [comment]
Yeah it is

**Comment by therealprof** [comment]
Interesting. How far are you with the MQTT 5 plans? I was just checking the code base and didn't see any obvious place to hook in the version handling and somewhat different MQTT 5 packets.

**Comment by tekjar** [comment]
@therealprof Haven't started the work yet. But that's the plan for the next 6 months. Might happen sooner if there's enough interest

**Comment by therealprof** [comment]
I'm very interested in MQTT 5 but I'm not quite sure where rumq fits in my picture. 😅 I might be able to contribute though.

**Comment by Progdrasil** [comment]
> Yeah it is. Redesigned to be fully async with tokio 0.2 and futures 0.3. But the work in the repo is much bigger than rumqtt
> 
>     * mqtt 5
> 
>     * distributed broker
> 
>     * quic support
> 
>     * web sockets
> 
> 
> are planned

Thanks for clearing that up! I was wondering why it was a rewrite and not just a ownership transfer. I'm also really excited for MQTT 5. 

Will there be a synchronous api ? As adding async to production with its current state is alightly nerve wracking.

**Comment by tekjar** [comment]
> Thanks for clearing that up! I was wondering why it was a rewrite and not just an ownership transfer.

That was the work done at my previous job after I found that the existing c libraries at that time weren't robust enough for Ather's use case. I'm not working there anymore. I asked for a ownership transfer but I didn't get any response back. I think it's better this way


> Will there be a synchronous api ? As adding async to production with its current state is alightly nerve wracking

What exactly is the issue? Is it the learning curve? Adding synchronous API by spawning a thread should be simple enough though. I don't have any opinions on this yet

**Comment by Progdrasil** [comment]
Last time I played with async it was mainly the compiled size that just exploded. And I have a constraint of reducing the space used for embedded linux work. That is just my specific use case though, so I was just wondering if a synchronous API has been considered or not. If not, I can work around that

**Comment by killercup** [comment]
MQTT 5 is also quite interesting to us.

I'm currently trying to find the "right" MQTT client library in Rust and rumq looks promising! How production-ready do you think it is right now, or, in April? I know you have experience writing MQTT libs but I don't want to just build something on top of rumq if you can tell me right now it'll in an experimental phase for a while :)

I'm not sure how much time I'll have to contribute to the implementation, but I'll try. My alternative right now would be to update the mosquitto binding, fyi.

**Comment by tekjar** [comment]
> How production-ready do you think it is right now, or, in April

I'm not sure of the robustness as this library hasn't seen much use in production yet. But the design came out good IMO. We are going to deploy this for a few partners we are working with closely in April. I expect things to get stable by the end of May.

But the test suite is getting ready. And I'm willing to work closely with people trying to use this in production and fix issues on priority (If they let me know that they have a production use case :) )
