### ISSUE TITLE
Mosquitto Vs Rumqttd

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytebeamio/rumqtt#192]
Hi,

Can I find the comparison between the Mosqitto Vs Rumqtt somewhere?. Please guide me to the location where can I find some evaluation number if any.

Thanks,
Pradeep

**Comment by tekjar** [comment]
Broker work is still ongoing. We are using single node broker in our prod but it's still beta. You can benchmark brokers with [mqttwrk](https://github.com/bytebeamio/mqttwrk)

There is no detailed comparison document yet
