### ISSUE TITLE
The provided config in example for rumqqtd does not compile.

### ISSUE THREAD

**Issue by MariusVB** [bytebeamio/rumqtt#194]
Hi,

I'm trying to set up the rumqqtd server, but I'm getting a compile error from the rumqttd.conf file. I've tried both with version 0.1 and the old config before #182, and with 0.2 and the current config. Both gives BadTomlData error. Error for 0.1 looks like this:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadTomlData(Error { inner: ErrorInner { kind: Custom, line: Some(16), col: 0, at: Some(359), message: "invalid type: map, expected a sequence", key: ["broker", "servers"] } })', src/main.rs:15:66

And the 0.2 error is:

> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadTomlData(Error { inner: ErrorInner { kind: Custom, line: Some(17), col: 4, at: Some(520), message: "missing field `broker`", key: [] } })', src/main.rs:15:66

Also, it seems you did not include 
`
extern crate pretty_env_logger;
`

At the top of the broker.rs file in rumqttd examples.

**Comment by tekjar** [comment]
I'll check these today. Thanks for reporting

**Comment by tekjar** [comment]
Can you check current master

**Comment by tekjar** [comment]
Feel free to reopen if current release doesn't solve your problem

**Comment by MariusVB** [comment]
Still not compiling and `use pretty_env_logger;` is stil missing in the broker.rs file.

Here's a verbose output:

`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: BadTomlData(Error { inner: ErrorInner { kind: Custom, line: Some(41), col: 0, at: Some(1206), message: "missing field `broker`", key: [] } })', src/main.rs:13:66
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e792288df31636ca28108516c63a00ce4267063a/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/e792288df31636ca28108516c63a00ce4267063a/library/core/src/panicking.rs:92:14
   2: core::option::expect_none_failed
             at /rustc/e792288df31636ca28108516c63a00ce4267063a/library/core/src/option.rs:1268:5
   3: core::result::Result<T,E>::unwrap
             at /home/marius/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:973:23
   4: mqtt_server::main
             at ./src/main.rs:13:26
   5: core::ops::function::FnOnce::call_once
             at /home/marius/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
`

**Comment by tekjar** [comment]
Are you sure you are using latest broker and config? Can you copy paste your config file and instructions you are using to run here

**Comment by MariusVB** [comment]
I've created a new cargo project.

Inside src I have main.rs, which is copy pasted from broker.rs:

```
use librumqttd::Broker;
use serde::{Deserialize, Serialize};
use std::thread;
use pretty_env_logger;

#[derive(Debug, Default, Serialize, Deserialize, Clone)]
struct Config {
    broker: librumqttd::Config,
}

fn main() {
    pretty_env_logger::init();
    let config: Config = confy::load_path("config/rumqttd.conf").unwrap();
    let mut broker = Broker::new(config.broker);

    let mut tx = broker.link("localclient").unwrap();
    thread::spawn(move || {
        broker.start().unwrap();
    });

    // connect to get a receiver
    // TODO: Connect with a function which return tx and rx to prevent
    // doing publishes before connecting
    // NOTE: Connection buffer should be atleast total number of possible
    // topics + 3 (request types). If inflight is full with more topics
    // in tracker, it's possible that router never responnds current
    // inflight requests. But other pending requests should still be able
    // to progress
    let mut rx = tx.connect(200).unwrap();
    tx.subscribe("#").unwrap();

    // subscribe and publish in a separate thread
    thread::spawn(move || {
        for _ in 0..10 {
            for i in 0..200 {
                let topic = format!("hello/{}/world", i);
                tx.publish(topic, false, vec![0; 1024]).unwrap();
            }
        }
    });

    let mut count = 0;
    loop {
        if let Some(message) = rx.recv().unwrap() {
            // println!("T = {}, P = {:?}", message.topic, message.payload.len());
            count += message.payload.len();
            println!("{}", count);
        }
    }
}
```

I have created a config folder, next to the src folder at the project root. Where I have pasted the config from `rumqttd.conf`:

```
# Broker id. Used to identify local node of the replication mesh
id = 0

# A commitlog read will pull full segment. Make sure that a segment isn't
# too big as async tcp writes readiness of one connection might affect tail
# latencies of other connection. Not a problem with preempting runtimes
[router]
id = 0
dir = "/tmp/rumqttd"
max_segment_size = 10240
max_segment_count = 10
max_connections = 10001

# Configuration of server and connections that it accepts
[servers.1]
port = 1883
next_connection_delay_ms = 1
    [servers.1.connections]
    connection_timeout_ms = 100
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 2048
    max_inflight_count = 500
    max_inflight_size = 1024

# Configuration of server and connections that it accepts
[servers.2]
port = 8883
cert_path = "tlsfiles/server.cert.pem"
key_path = "tlsfiles/server.key.pem"
ca_path = "tlsfiles/ca-chain.cert.pem"
next_connection_delay_ms = 10
    # Tls connections. ca_path enables client authentication
    [servers.2.connections]
    connection_timeout_ms = 100
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 2048
    max_inflight_count = 100
    max_inflight_size = 1024

[console]
port = 3030
```

That is all I have.

**Comment by tekjar** [comment]
You are trying to deserialize config file into a different structure
```
#[derive(Debug, Default, Serialize, Deserialize, Clone)]
struct Config {
    broker: librumqttd::Config,
}
```

You need to add `broker.` prefix to all the toml entries. Here is an example of how we embed

```
       │ File: config/beamd.conf
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1   │ # Broker id. Used to identify local node of the replication mesh
   2   │ [broker]
   3   │ id = 0
   4   │ 
   5   │ # A commitlog read will pull full segment. Make sure that a segment isn't
   6   │ # too big as async tcp writes readiness of one connection might affect tail
   7   │ # latencies of other connection. Not a problem with preempting runtimes
   8   │ [broker.router]
   9   │ id = 0
  10   │ dir = "/tmp/rumqttd"
  11   │ max_segment_size = 10240
  12   │ max_segment_count = 10
  13   │ max_connections = 10001
  14   │ 
  15   │ # Configuration of server and connections that it accepts
  16   │ [broker.servers.1]
  17   │ port = 1883
  18   │ next_connection_delay_ms = 1
  19   │     [broker.servers.1.connections]
  20   │     connection_timeout_ms = 100
  21   │     max_client_id_len = 256
```

**Comment by tekjar** [comment]
> Also, it seems you did not include
> `extern crate pretty_env_logger;`

This isn't necessary in rust 2018

**Comment by MariusVB** [comment]
Here's the PR:
https://github.com/bytebeamio/rumqtt/pull/210

> This isn't necessary in rust 2018. I could directly add `pretty_env_logger::init()` as long as the dependency exists in `Cargo.toml`

Weird, I'm using the latest rust stable 1.48? What am I missing?

**Comment by MariusVB** [comment]
Works now!
