### ISSUE TITLE
Use feature flags to switch between mqtt 4 and 5

### ISSUE THREAD

**Issue by tekjar** [bytebeamio/rumqtt#196]
Convert if conditions to feature flags in mqttbytes

**Comment by thalesfragoso** [comment]
Won't that prevent a dependent crate from supporting both mqtt 4 and 5 ?

**Comment by tekjar** [comment]
It does. But I feel not many want to use 4 and 5 together in the same client

**Comment by jplatte** [comment]
I like the idea of having feature flags for mqtt4 and mqtt5 support, but I agree with @thalesfragoso that they should not be mutually exclusive. Is there some reason why they'd have to be?

**Comment by tekjar** [comment]
Mqtt 5 is mostly compatible with mqtt 4. This allows to use same data structures and code for the most part. But using mqtt5 specifics dynamically with `if` conditions is causing perf degradation because of some large enums on stack.

https://github.com/bytebeamio/rumqtt/blob/master/mqttbytes/src/packets/publish.rs#L15-L16

Also I couldn't think of a reason why client code would want to use 4 and 5 at the same time

**Comment by therealprof** [comment]
> Also I couldn't think of a reason why client code would want to use 4 and 5 at the same time

Not concurrently but you certainly might have an implementation which allows configuration of the protocol version at runtime rather requiring a recompilation.

**Comment by therealprof** [comment]
I should add that `rumqttd` most certainly should be able to support both concurrently.

**Comment by tekjar** [comment]
@therealprof Yes. I think I drove myself to a corner. I've only realized now that cargo features are all additive. I assumed that I would be able to depend on a crate twice with different features enabled (which is wrong)

**Comment by jplatte** [comment]
Sounds like you really just need generics. Have a generic parameter for the protocol with mqtt4 and mqtt5 types that can be used for it implementing a common trait that contains functions for the version-specific behavior.

**Comment by tekjar** [comment]
mqtt 5 and 4 are separate modules now

**Comment by skreborn** [comment]
@tekjar I understand that `v4` and `v5` are now separate modules under `mqttbytes`, but this doesn't actually allow us to use them through `rumqttc` and `rumqttd`, does it? It seems to me that all of the crates are now just riddled with `v4` hardcoded into their use lists.

**Comment by tekjar** [comment]
`mqttbytes` will be used inside rumqttc and rumqttd. `rumqttc` and `rumqttd` handles the details of v4 and v5 and user code wont be riddled with version details

**Comment by skreborn** [comment]
That is, of course, an excellent approach. I'm guessing they only need to make the version difference available to the user when new features of `v5` are used. I'm especially interested in custom properties, which are implemented right now in `mqttbytes::v5` as far as I can tell, but I don't yet see a way to make use of it from an application. Is this something that's being worked on in the shadows, or something you'd accept contributions for?

**Comment by tekjar** [comment]
I'm privately working on when I get time. But nothing to show yet. PRs are ofcourse welcome
