### ISSUE TITLE
Replace index access with get in state

### ISSUE THREAD

**Issue by tekjar** [bytebeamio/rumqtt#201]
Replace indexing in broker and client [state](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/src/state.rs#L221) to prevent crashes due to bad brokers or clients.

**Comment by haja** [comment]
I was thinking about working on this issue, but the task is not really clear to me.  
Are you referring to `outgoing_pub`, `outgoing_rel` and `incoming_pub`?  
Can you elaborate a bit more?

**Comment by tekjar** [comment]
Yeah. For e.g [this](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/src/state.rs#L228). Wrong pkids would crash the client
