### ISSUE TITLE
Embeded broker

### ISSUE THREAD

**Issue by RepentantGopher** [bytebeamio/rumqtt#207]
Hello! 
I want to build embeding mqtt broker for Tarantool based on your fantastic library and after browsing source code i have several questions:
 -  In current broker implementation there are no options for auth incomming clients. How can i auth incomming connections? Can i dynamically check login / password on app side not on broker side?
 -  I want to let users implements custom logic on publishing message / subscribing on topics, for example, do not let some clients publishing in certain topics. I think it could be achieved via some registered callbacks which will be called on every publishing message inside broker / subscribing on topics. Is it possible?

**Comment by tekjar** [comment]
> * In current broker implementation there are no options for auth incomming clients. How can i auth incomming connections? Can i dynamically check login / password on app side not on broker side?

I never had an usecase for username password. Can you raise a separate issue for this?



> * I want to let users implements custom logic on publishing message / subscribing on topics, for example, do not let some clients publishing in certain topics. I think it could be achieved via some registered callbacks which will be called on every publishing message inside broker / subscribing on topics. Is it possible?

Not possible at the moment. Access control rules are in the roadmap though.
