### ISSUE TITLE
Error when executing "simple asynchronous publish and subscribe" example

### ISSUE THREAD

**Issue by brinoausrino** [bytebeamio/rumqtt#238]
When executing [simple asynchronous publish and subscribe](https://docs.rs/rumqttc/0.5.0/rumqttc/#a-simple-asynchronous-publish-and-subscribe) example I run into the following issue:

`thread 'main' panicked at 'there is no reactor running, must be called from the context of a Tokio 1.x runtime'`

How could I fix this?
Thanks in advance

**Comment by jplatte** [comment]
Sounds like you have a dependency on an older version of tokio. As the error message says, you need tokio 1.x.

**Comment by brinoausrino** [comment]
That's strange, since my cargo.toml includes such a version

```
[dependencies]
futures = "0.3.12"
rumqttc = "0.5.0"
tokio = "1.1.0"
```
Or is there some other kind of dependency (btw. I'm new at programming rust)?

**Comment by jplatte** [comment]
What's the declaration of your `fn main`? Is it an `async fn main`? Usually you'd use `#[tokio::main]` to start the tokio runtime at the start of a central function (`main` or a function directly called by it).

**Comment by brinoausrino** [comment]
This works! Thank you very much.

Just for the record:

```
// before - DOES NOT WORK
fn main() {
    let future = mqtt_client::connect_to_server();
    block_on(future); 
}
```

```
// after - WORKS
#[tokio::main] 
async fn main() {
    let future = mqtt_client::connect_to_server();
    block_on(future); 
}
```

**Comment by jplatte** [comment]
@brinoausrino you seem to be missing some more context. I recommend you read some introductory content about async in Rust, for example

* [Asynchronous Programming in Rust](https://rust-lang.github.io/async-book/)
* [The Tokio tutorial](https://tokio.rs/tokio/tutorial)
