### ISSUE TITLE
Unstable connection, how to debug?

### ISSUE THREAD

**Issue by korken89** [bytebeamio/rumqtt#244]
Hi,

I have been testing this library with a very simple test code to see how it performs for subscribing to a stream.
For reference I use `mosquitto_sub`. 

What I notice is that with this library about every 3-10 seconds I loose the connection to our broker and need to wait for reconnect.
I am not seeing this issue with `mosquitto_sub` which I run in parallel to compare.

How does one start to debug an issue like this?
I'm using version `0.31`.

Test code:

```rust
use rumqtt::{MqttClient, MqttOptions, QoS};

fn main() {
    let mqtt_options = MqttOptions::new("test-pubsub1", "myserver", 1883);
    let (mut mqtt_client, notifications) = MqttClient::start(mqtt_options).unwrap();
      
    mqtt_client.subscribe("#", QoS::AtLeastOnce).unwrap();
    
    for notification in notifications {
        println!("{:?}", notification)
    }
}
```

and comparison command:

```console
mosquitto_sub -h myserver -t "#" -v
```

**Comment by tekjar** [comment]
Hi @korken89. rumqtt 0.31 was the work I did for my previous employer. I've no control of that crate now and the repo is archived to avoid confusion. All the new work happens in these crates

client: [rumqttc](https://crates.io/crates/rumqttc)
broker: [rumqttd](https://crates.io/crates/rumqttd)

PS: Big fan of your work, especially your phd thesis and I regularly follow your work on stereo cameras

**Comment by korken89** [comment]
@tekjar Haha thanks, this makes a lot of sense! xD
Thanks for getting me on the right path!

Also really fun to have a follower :D
