### ISSUE TITLE
`start` function in `router.rs` starves other threads/tasks 

### ISSUE THREAD

**Issue by jaredwolff** [bytebeamio/rumqtt#245]
When implemented among other threads/tasks, the `start` function does not yield. Meaning it runs indefinitely blocking other tasks from processing. See #242 for potential solution.

For example in the `async_broker.rs` example, a thread is created to run the router:

```rust
    thread::spawn(move || {
        router.start().unwrap();
    });
```

While this works standalone when you start using a runtime like Tokio with other tasks running in the background, it does not yield as far as I can tell. With the suggestions made in #242, the tasks that I was attempting to initialize in `pyrinas` _after_ initializing rumqqtd actually began running. Whereas before, they never started up. And previous tasks that were initialized stoped operating as well.

This could also be very platform dependent. I found that sometimes it would work on my Mac but not my FreeBSD server. Depends on how the scheduler works in the OS. Best to avoid non-yielding loops like this and instead enqueue events into a channel.

**Comment by jaredwolff** [comment]
As mentioned in #242, the `start` function should not be run in a Tokio task. Which makes sense. Though the example in this repository uses `thread::spawn` and I see the same exact blocking behavior. I'll try `task::spawn_blocking` as recommended by @tekjar.

Is there an advantage to having that function constantly running rather than go to idle and async wait for tasks to be sent its way? Maybe I missed that in our earlier discussion.

**Comment by tekjar** [comment]
> Though the example in this repository uses `thread::spawn` and I see the same exact blocking behavior.

You mean this thread is starving other threads?

> By the way, is there an advantage to having that function constantly running rather than go to idle and async wait for tasks to be sent its way? Maybe I missed that in our earlier discussion.

function is not constantly running. It goes idle [here](https://github.com/bytebeamio/rumqtt/blob/master/rumqttlog/src/router/router.rs#L108) and waits (consuming 0 cpu). Router is very cpu heavy, not io heavy. So thread is a better choice here IMO

**Comment by jaredwolff** [comment]
Finally was able to test. Tokio's `task::spawn_blocking` fixes the issue that I was seeing. Closing this out.
