### ISSUE TITLE
MQTT v3.1.1 connack return codes not recognized

### ISSUE THREAD

**Issue by jplatte** [bytebeamio/rumqtt#249]
It seems like some MQTTv5 work broke the connack return codes for v3.1.1. None of them are recognized right now, e.g. authorization failure leads to `InvalidConnectReturnCode(5)`.

https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Table_3.1_-

**Comment by tekjar** [comment]
Can you check if current master fixes this?

**Comment by jplatte** [comment]
It does. Now getting `I/O: Broker rejected. Reason = NotAuthorized` on auth failure. I still very much dislike this being crammed into the IO error variant, but that's a separate issue (which I might write a patch for soon).
