### ISSUE TITLE
Implement exponential backoff when connection fails

### ISSUE THREAD

**Issue by jplatte** [bytebeamio/rumqtt#251]
I couldn't find any issues about this so I'm assuming that it hasn't been implemented yet (we're using an older version of rumqttc currently because we're still on tokio 0.2). Currently rumqttc retries connecting way too often if it fails.

There is a [backoff crate](https://crates.io/crates/backoff) that could help with this.

**Comment by amrx101** [comment]
I actually had this implemented for my own use. I think I will let @tekjar take a call on this, whether we need this?

**Comment by tekjar** [comment]
Would like to keep the reconnection logic simple until 1.0. Please feel free to reopen this after that
