### ISSUE TITLE
ConnAck with non-success code being transformed to ConnectionError::Io is very confusing

### ISSUE THREAD

**Issue by jplatte** [bytebeamio/rumqtt#252]
When trying to catch auth errors to add special error handling for them, the first thing I reached for was splitting a previous

```rust
Event::Incoming(Incoming::ConnAck(_)) => // ...
```

match pattern into

```rust
Event::Incoming(Incoming::ConnAck(ConnAck {
    code: ConnectReturnCode::Success,
    ..
} => // success
Event::Incoming(Incoming::ConnAck(ConnAck { code, .. })) => {
    // failed with code
}
```

but was surprised that the latter reached when authorization failed. After looking at what error got generated, I now updated the `.poll().await` return handling to

```rust
Err(ConnectionError::Io(io)) => {
    let error_msg = match io.kind() {
        ErrorKind::ConnectionRefused => {
            "Failed to connect to MQTT (connection refused)"
        }

        _ if io.to_string().ends_with("NotAuthorized") => {
            "Failed to connect to MQTT (not authorized)"
        }

        // ...
    };

    // ...
}
```

But that seems super brittle. Please just stop turning `ConnAck`s with `code != Success` into errors at all, or at least turn them into a separate `ConnectionError::Server(ConnectReturnCode)` variant or something like that.

**Comment by jplatte** [comment]
I'm no longer using rumqttc. I can ping my former colleagues though, maybe sbd. wants to verify this.

**Comment by FSMaxB** [comment]
Will check this out once I find the time to do so.

**Comment by FSMaxB** [comment]
Sorry for taking such a long time :sweat_smile:.

I have now verified that it is fixed, thanks a lot!
