### ISSUE TITLE
on connection successful callbacks

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytebeamio/rumqtt#253]
Hi,

Are there callbacks like on_connect, on_disconnect etc call backs in rumqttc?
Can we set these call backs on a client handle?

Regards,
Pradeep

**Comment by tekjar** [comment]
[Eventloop.poll](https://docs.rs/rumqttc/0.5.0/rumqttc/struct.EventLoop.html#impl) notifications can detect these
