### ISSUE TITLE
[Broker] Auth connection

### ISSUE THREAD

**Issue by cyrixSpec** [bytebeamio/rumqtt#254]
Hi there,
is it possile to implement auth (username, password) on the broker-side for incoming connections?

Thanks in advance.

**Comment by tekjar** [comment]
Hi @cyrixSpec . Apologies for the delay. Yeah that should be easy enough but unfortunately I don't have the bandwidth now. But I can help with implementation and PRs.

**Comment by jaredwolff** [comment]
@cyrixSpec should be added now. Give it a whirl and let us know if you run into any snags.
