### ISSUE TITLE
rumqttd: does not close network socket on timeout

### ISSUE THREAD

**Issue by jaredwolff** [bytebeamio/rumqtt#259]
It appears currently when there's a connection timeout, a disconnection event is forwarded to the router and then the router sends a disconnection event via MQTT itself. But what if that message never is received? The client never disconnects the socket and the socket on the server side is maintained (as it's never released/closed). This could lead to a phantom connection whereas the client thinks it's connected whereas the server has "disconnected" from the client.  

For example: I was running one setup over night noticed that the client was online (via cellular) but had "disconnected" due to a timeout hours prior:

```
[2021-03-03T10:12:46Z ERROR librumqttd] Error!! Id = <ID> (14), Network Keep alive timeout
[2021-03-03T10:12:46Z INFO  rumqttlog::router::router] disconnect                 Id = <ID>:14
```

Correct me if I'm wrong but shouldn't the socket be closed matter what after executing the last messages? Or should it not even attempt to do that in an event of a timeout? My timeout is set to 65 seconds whereas the clients send a ping every 55 or so.

**Comment by jaredwolff** [comment]
Or should it be dropped after new_connection returns? I did notice that the stream is not initialized in the same task as the rest of the connection work. Working through it and trying to replicate..

**Comment by tekjar** [comment]
I did not understand the complete context of this but if you are talking about half open connections, keep alive handles them.

Assume client has connected with keep alive time of 10 seconds. After a successful connection server expects a message with in that timeout. If there is no message, server will disconnect it and there is no half open connection which lives indefinitely. Both server and client are equipped to clean themselves up in these cases. If you talking about cases where keep alive = 0, then yes this is a problem.



> For example: I was running one setup over night noticed that the client was online (via cellular) but had "disconnected" due to a timeout hours prior:

This is weird if you have a keep alive which is > 0. Which client is this? rumqttc?

**Comment by jaredwolff** [comment]
I couldn't replicate this so we can ignore for now. Thanks @tekjar
