### ISSUE TITLE
Does rumqtt support shared  subscription?

### ISSUE THREAD

**Issue by piaoger** [bytebeamio/rumqtt#269]
Is there an way to make one message  can be consumed  by only one subscriber in  rumqtt ?

**Comment by tekjar** [comment]
Shared subscriptions are not supported yet. But at one point they'll be. Cannot commit any time yet.

**Comment by swanandx** [comment]
Hey @piaoger , support for shared subscriptions is planned and will be supported soon. Will be closing this issue in favor of #621 , you can track the progress there.
