### ISSUE TITLE
TLS Client Authentication

### ISSUE THREAD

**Issue by jaredwolff** [bytebeamio/rumqtt#278]
Now that #257 has been addressed, I also noticed that `native-tls` does not have client authentication (`rustls` does). That means that the connection is encrypted but any client can connect. That's somewhat mitigated with the MQTT password, but ideally each client should be authenticated separately. 

For now this is a placeholder for future improvements.

**Comment by tekjar** [comment]
Hi @jaredwolff . We've recently started using native tls that you've contributed. Have you checked if a PR to support client authentication in native tls crate is straight forward?

**Comment by de-sh** [comment]
Solved by #378

**Comment by tekjar** [comment]
native-tls doesn't look like it will support client authentication anytime soon. Probably a simple jwt based authentication can be added to client and broker. Closing this for now. Please feel free to reopen this when there is relevant progress in native-tls
