### ISSUE TITLE
Roadmap: Plans regarding MQTTv5?

### ISSUE THREAD

**Issue by flxo** [bytebeamio/rumqtt#284]
Hello,

I haven't found much regarding the roadmap of `rumqtt` - especially v5. 
In #19 there's a mention. Would be great if @tekjar could give a short summary what are the current activities or plans? I can add this afterwards to the readme.

thanks!

@flxo

**Comment by tekjar** [comment]
@flxo Unfortunately mqtt 5 work hasn't started yet as we've prioritized other stuff. Serialization and deserialization is done though.  A lot of work is happening in private repos as we couldn't keep up with opensource support. We are in the process of hiring and this should improve soon. 

OTOH, what do you need now? Mqtt 5 broker or client? I'll try to escalate this internally

**Comment by flxo** [comment]
> @flxo Unfortunately mqtt 5 work hasn't started yet as we've prioritized other stuff. Serialization and deserialization is done though. A lot of work is happening in private repos as we couldn't keep up with opensource support. We are in the process of hiring and this should improve soon.
> 
> OTOH, what do you need now? Mqtt 5 broker or client? I'll try to escalate this internally

Thanks for your reply. I'm mainly interested in the the broker part since the client libs we use have v5 support (C and Java).

**Comment by tekjar** [comment]
Cool. Can you let me know the features that are important to you in mqtt 5? (E.g. topic aliases)

**Comment by flxo** [comment]
The feature that is most used in our scenario are user properties and auth.

**Comment by yguel** [comment]
Do you have any update on that ? 
We are migrating projects to rust and are looking for a mqtt broker in rust, opensource, that we could contribute to.
For us, the main use-case for v5 is the request-response pattern.
We would eagerly contribute to a rust implementation to make that feature available.

**Comment by de-sh** [comment]
Hey @yguel, we are working on this with #351. We'd love to get any insights that you'd have for us.

CC: @abhikjain360

**Comment by yguel** [comment]
@de-sh great we will check that !

**Comment by swanandx** [comment]
Hey, update on the progess:
- rumqttc now [supports](https://bytebeam.io/blog/rumqttc-now-supports-mqtt5-3/) MQTTv5! 
- rumqttd supporting MQTTv5 is WIP and making progress rapidly. You can track the progress here:  #621 

Closing this issue in favor of the above mentioned issue. Thank you!
