### ISSUE TITLE
Repository not lining up with published crate(s)?

### ISSUE THREAD

**Issue by therealprof** [bytebeamio/rumqtt#285]
I'm looking at the `mqttbytes` crate which was just published as `0.4.0` but the `Cargo.toml` is still at `0.3.0`. Not sure how that is possible but it's not a good state.

Also the `CHANGELOG.md` is out of date...

**Comment by nothingismagick** [comment]
This can happen if the author is pushing from local instead of doing it within CI.
This is a little disturbing though:
https://github.com/bytebeamio/rumqtt/blob/e0d459df066033dc1b51adc205b453814dda70e3/.github/workflows/master.yml#L28

**Comment by therealprof** [comment]
@nothingismagick I'm aware. But even then I'd expect that the author would retroactively push the missing commits. Now I'm wondering what else happened in the 10 days since the last push apart from the missing release data in `Cargo.toml`...

**Comment by nothingismagick** [comment]
I totally agree. This smells.

**Comment by tekjar** [comment]
@therealprof @nothingismagick  Sorry for that. I usually create a release branch, push it, cargo publish and then merge release branch to master.

I messed up the order. This is a result of not automating the release flow. But unfortunately don't have the bandwidth

**Comment by tekjar** [comment]
Also any PRs improving the release flow are welcome. A lot of work is happening in private repos now as I couldn't keep up with opensource support. We are in the process of hiring and hopefully support will be much better soon

**Comment by tekjar** [comment]
This is sorted
