### ISSUE TITLE
error[E0658]: use of unstable library feature 'wake_trait'

### ISSUE THREAD

**Issue by awsa2ron** [bytebeamio/rumqtt#289]
Only happens on my MacOS.
```
rustup --version
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.52.1 (9bc8c42bb 2021-05-09)`
```
No error on my Ubuntu PC. FYI.

**Comment by awsa2ron** [comment]
It works on my another apple M1 MacBook. I suppose the only difference is that the toolchain is changed to "stable-aarch64-apple-darwin"

**Comment by growse** [comment]
I had this issue, but then updated to rust `1.53.0` and it started working. Related: https://github.com/zesterer/pollster/issues/6 ?

**Comment by de-sh** [comment]
This issue seems to be solved, please reopen if required.
