### ISSUE TITLE
max packet size

### ISSUE THREAD

**Issue by PradeepKiruvale** [bytebeamio/rumqtt#296]
I see the packet size in the rumqttc is capped to 10k. 
Any reason why its capped at this size?.
Also is there any way to configure this?.
Asking this because Mosquitto broker caps at 256MB, but the clients implemented using the  rumqttc can not use bigger than 10k.

**Comment by jplatte** [comment]
This can be configured: https://docs.rs/rumqttc/0.7.0/rumqttc/struct.MqttOptions.html#method.set_max_packet_size
