### ISSUE TITLE
Can we get binary size to be smaller

### ISSUE THREAD

**Issue by detly** [bytebeamio/rumqtt#299]
I have compiled and run the demo client project with TLS, under Rust stable 1.54. Even if I remove/replace some of the dependencies (`pretty_env_logger` with `env_logger` minus some features, `tokio` with default feature set, not `full`), the resulting binary is 2.0MB for a release build *after* stripping debug symbols.

I am targeting an embedded Linux platform running OpenWRT, with about 16MB of total flash space, and about 6MB to spare. 2.0MB for the MQTT equivalent of a "Hello, world!" program is quite substantial in this context. On the scale of Rust binaries it's actually not that bad — a basic Calloop program is about 350kB, and one of my other fully featured services (still Calloop based) is about 700kB - 1.3MB. But the fundamental problem is that if I want to write the MQTT parts in Rust, that's about four other parts I need to keep in C. For comparison, the total size of the current MQTT system, written in C (using libuv and mosquitto), is 65kB (with dynamically linked musl).

Would you have any interest in trying to get the binary size down for such a use case? It is extremely hard to determine what packages contribute to the size, although `cargo bloat` helps. `std` is the biggest (no surprises there), and `rustls` and `ring` are also substantial, but essential. Tokio is next on the list.

Given that, the only strategies I can think of off the top of my head are:

- feature-gating a few more things, if that is at all possible
- allowing non-Tokio runtimes (eg. Smol) or adaptation into event loops based on file-descriptors (eg. Calloop)

I could contribute in the sense of testing and more detailed accounting of size, but I'm not familiar enough with the depths of rumqtt to make changes with a lot of confidence (yet). I opened this issue mainly to (a) gauge your own interest in making code size smaller and (b) keep notes or focus efforts if other people want to work on it.

**Comment by de-sh** [comment]
We are working on feature-gating functions such as TLS, but don't believe it will be easy for us to transition away from tokio.

**Comment by detly** [comment]
Okay, that's fair enough. If I identify specific things that would reduce binary size in the future, I'll open an issue or PR for it separately. This one can probably be closed. I can see if tokio itself has any gains to be made in this respect, too.
