### ISSUE TITLE
Get informations about subscriptions

### ISSUE THREAD

**Issue by samuel-rufi** [bytebeamio/rumqtt#304]
Hello, I'm wondering if it's possible to get informations about subscriptions in `rumqttd`?
For example if an user subscribes `testtopic/xyz`, is it somehow possible to get a notification about it so that I´m able to extract the topic string? Unfortunately I couldn´t figure out how to do this.

Many thanks for help.

**Comment by rufsam** [comment]
@tekjar sorry for the ping, but maybe you can help me with that issue? thanks alot!

**Comment by henil** [comment]
hey @samuel-rufi, this was implemented in AlertLink (https://github.com/bytebeamio/rumqtt/pull/538) and it was merged and released in `rumqttd 0.12.2`. 

If you have any questions or feedback feel free to join our [discord](https://discord.gg/mpkSqDg) and let us know.
