### ISSUE TITLE
Pure Rust support (make rustls optional)

### ISSUE THREAD

**Issue by terorie** [bytebeamio/rumqtt#305]
`rumqttc` has the dependency chain `tokio-rustls` => `rustls` => `ring` => `cc`.

This makes builds of `rumqttc` fail in pure Rust environments (no C compiler).
Since `rumqttc` advertises itself in Cargo as a pure Rust client, it would be nice to make TLS support a feature that can be disabled to ensure pure Rust support.

**Comment by svet-b** [comment]
In favor of this also, though for a different reason. We're working in an embedded environment, and although we'd like to use this library, the binaries produced by `paho-mqtt` are significantly smaller (e.g. 500KB vs 2MB, for the same minimal functionality). We don't need TLS, so having a way to disable it would help close this size gap.
