### ISSUE TITLE
Release a new version to crates.io with the latest changes

### ISSUE THREAD

**Issue by Thoralf-M** [bytebeamio/rumqtt#306]
@tekjar would it be possible to do a new release to crates.io with the latest changes? Would be great because otherwise we can't release a new version for our crate

**Comment by tekjar** [comment]
Just released a new version. Can you please check and close this issue?

**Comment by Thoralf-M** [comment]
Hey @tekjar, thanks for doing it, but unfortunately this commit https://github.com/bytebeamio/rumqtt/commit/b0b1d1228a01a6b28858c4039f4ca163c1e73060 breaks it since `UnixStream` only works with the `net` feature of tokio and on Unix, but we want to use it also on other platforms 😢

**Comment by Thoralf-M** [comment]
Thanks!
