### ISSUE TITLE
Test compilation fails, and test is failing

### ISSUE THREAD

**Issue by haja** [bytebeamio/rumqtt#315]
On current master (~e177e3a), `rumqttc/examples/tls2.rs` is currently not compiling and failing the CI (dependency on a local path for a certificate file).  
Uncommenting that code reveals that test `rumqttc/tests/reliability.rs packet_id_collisions_are_detected_and_flow_control_is_applied()` is failing on my machine.

Is this an issue with my setup, or is there something broken with the project?

**Comment by de-sh** [comment]
Hey @haja sorry for the late reply. Seems like this issue was partially solved by https://github.com/bytebeamio/rumqtt/commit/629320dcc2f4635ca93208af58174b7049252183 and test seems to be working properly on my machine. Can you give more specifics like what the test failure message said?
