### ISSUE TITLE
Generic string arguments

### ISSUE THREAD

**Issue by destenson** [bytebeamio/rumqtt#327]
There are a number of functions that take multiple `<S: Into<String>>` arguments. For example:

```
    pub fn set_credentials<S: Into<String>>(&mut self, username: S, password: S) -> &mut Self {
        self.credentials = Some((username.into(), password.into()));
        self
    }
```

 This forces each argument to be of the exact same type. I don't think this is the desired behavior. It's certainly not what I would want. I would want to be able to pass two different `Into<String>` arguments, and their specific types shouldn't matter, as long as they implement `Into<String>`.

**Comment by tekjar** [comment]
Sure! Would you like to send a PR?
