### ISSUE TITLE
Potentially make `ClientError` and `ConnectionError` `PartialEq`

### ISSUE THREAD

**Issue by TheNeikos** [bytebeamio/rumqtt#340]
Currently both `rumqttc::ClientError` and `rumqttc::ConnectionError` are not `PartialEq` making it impossible to check for equality (in a test for example).

Could this be added (and/or would you accept a PR doing so?)

Doing a cursory check through the different enum branches, none of the variants have a field that could not also be made `PartialEq`.

Cheers!

**Comment by de-sh** [comment]
Hey @TheNeikos , thank for opening this issue. After a cursory look through the definitions of these error types it seems like the error information that `ConnectionError` might enclose includes `io::Error` which also don't implement `PartialEq`. How would you propose we solve this problem?

**Comment by TheNeikos** [comment]
@de-sh You're right, I missed that when scanning for potential problems. 

I don't think this is a change that can then be safely(or sanely) added without causing other issues down the line. 

`io::Error` also can't implement `PartialEq` because it has this variant in it: https://doc.rust-lang.org/src/std/io/error.rs.html#74 (Which I frankly consider an error in hindsight, but I digress)

Thank you for your answer!
