### ISSUE TITLE
Isn't PUBREC/REL/COMP Acknowledgement to QoS2 publish?

### ISSUE THREAD

**Issue by shikoku1** [bytebeamio/rumqtt#347]
The comment / documentation is probably wrong

https://github.com/bytebeamio/rumqtt/blob/663a6845d640c2fa4adf822bf5c3b26435a198b5/mqttbytes/src/v4/pubrec.rs#L4-L6

https://github.com/bytebeamio/rumqtt/blob/663a6845d640c2fa4adf822bf5c3b26435a198b5/mqttbytes/src/v4/pubrel.rs#L4-L6

https://github.com/bytebeamio/rumqtt/blob/663a6845d640c2fa4adf822bf5c3b26435a198b5/mqttbytes/src/v4/pubcomp.rs#L4-L6

https://github.com/bytebeamio/rumqtt/search?q=Acknowledgement+to+QoS1+publish

http://public.dhe.ibm.com/software/dw/webservices/ws-mqtt/MQTT_V3.1_Protocol_Specific.pdf

**Comment by de-sh** [comment]
Well spotted, would you like to open a PR to solve this?
