### ISSUE TITLE
Why does MqttOptions take String for address?

### ISSUE THREAD

**Issue by matthiasbeyer** [bytebeamio/rumqtt#355]
Hi,

I am a bit confused on where the error handling for invalid endpoints is done in this library? From the docs, I can see that `MqttOptions::new` takes `String` for the address to connect to... so there won't be error handling. But when instantiating an `AsyncClient` with the `MqttOptions` object, the constructor also does not return `Result`, ... so where is the error handling done actually?

Maybe I am just missing something?

**Comment by de-sh** [comment]
Good question, the error would only popup when [polling the eventloop](https://github.com/bytebeamio/rumqtt/blob/master/rumqttc/src/eventloop.rs#L124)

**Comment by de-sh** [comment]
Hey @matthiasbeyer, hope the above comment answered your query. Closing the issue, please reopen if you still have any doubts.
