### ISSUE TITLE
Please provide a script to test the rumqttd with tls

### ISSUE THREAD

**Issue by lu-zero** [bytebeamio/rumqtt#367]
webpki/rustls have a know pitfall https://github.com/briansmith/webpki/issues/90 https://github.com/rustls/rustls/issues/127

Could you please add a gen.sh with the correct options to test the server? (or use https://github.com/est31/rcgen)

**Comment by tekjar** [comment]
@lu-zero You can use [this](https://github.com/bytebeamio/provision) to generates certificates. It sets `SAN` correctly in the way rustls expects
