### ISSUE TITLE
Support for `native-tls` in client

### ISSUE THREAD

**Issue by mladedav** [bytebeamio/rumqtt#377]
I have seen that the support was added to the server in #258, however, I would need to use something different than `rustls` in the client. This is because there is no cipher that is both in `rustls` and can be used for connecting to Azure IoT Hub.

**Comment by de-sh** [comment]
Hey @mladedav, we'd love to include `native-tls`, are you interested in contributing the same?

**Comment by mladedav** [comment]
I will see what I can do, but I have never used `native-tls` and have only a very limitted experience with this crate and `rustls` (as in I have just tried to make it work earlier this week). So progress may be slow.

I'll see if I can make this work and report here if I do or if I'll need some help.

**Comment by de-sh** [comment]
This is a continuation of #153
