### ISSUE TITLE
Check authorization when connecting

### ISSUE THREAD

**Issue by tingfeng-key** [bytebeamio/rumqtt#383]
I want to check the authorization of each client's connection, so as to avoid other connection subscriptions. Is there any way to deal with it at present? Thank you

**Comment by swanandx** [comment]
Hey @tingfeng-key , please excuse the delayed response. rumqttd do support authorization based on username and passoword. You can set them in `rumqttd.toml`. refer to [this](https://github.com/bytebeamio/rumqtt/blob/main/rumqttd/rumqttd.toml) example config file.
