### ISSUE TITLE
subscribe_many with empty topic list emits malformed packet

### ISSUE THREAD

**Issue by KisImre** [bytebeamio/rumqtt#387]
## Description

Calling `Client::subscribe_many` with an empty topic list causes it to send a subscribe packet without any topic filter. According to [[MQTT-3.8.3-3]](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718066) "The payload of a SUBSCRIBE packet MUST contain at least one Topic Filter / QoS pair. A SUBSCRIBE packet with no payload is a protocol violation". v5 has the same requirement. When the broker gets this message is closes the connection due to a malformed packet.

- This affects `try_subscribe_many` as well
- `Client::subscribe_many` should return an error when called with an empty topic list
- I haven't looked into rumqttd but it shouldn't accept these empty subscribe messages

## Test setup

rumqttc v0.12.0
mosquitto version 2.0.14

### Test code
```
use rumqttc::{Client, MqttOptions};

fn main() {
    let mqttoptions = MqttOptions::new("rumqtt-sync", "localhost", 1883);

    let (mut client, mut connection) = Client::new(mqttoptions, 10);

    client.subscribe_many(Vec::new()).unwrap();

    for notification in connection.iter() {
        println!("Notification = {:?}", notification);
    }
}
```

### Output
```
Notification = Ok(Incoming(ConnAck(ConnAck { session_present: false, code: Success })))
Notification = Ok(Outgoing(Subscribe(1)))
Notification = Err(MqttState(Io(Custom { kind: ConnectionAborted, error: "connection closed by peer" })))
```

### Broker log
```
mosquitto[2575]: 1650909678: New connection from ::1:39042 on port 1883.
mosquitto[2575]: 1650909678: New client connected from ::1:39042 as rumqtt-sync (p2, c1, k60).
mosquitto[2575]: 1650909678: Client rumqtt-sync disconnected due to malformed packet.
```

### Packet
![image](https://user-images.githubusercontent.com/2251170/165151913-20292867-2ff0-4edf-999f-a19c337d6d81.png)

**Comment by de-sh** [comment]
Thank you for pointing this out @KisImre. I have opened a branch to work on a possible solution to this. Do let me know your thoughts on the [included changes](https://github.com/bytebeamio/rumqtt/commit/96f863a5c523625e5e70deb52a07386dec43927f).

**Comment by KisImre** [comment]
Thank you for the fix, it looks good to me. Maybe it would be worth adding a check to `Subscribe::read` as well to prevent future issues.
