### ISSUE TITLE
Failed to build rumqttd due to the failure of building jemalloc 

### ISSUE THREAD

**Issue by di-otter** [bytebeamio/rumqtt#404]
After introducing rumqttd as the local broker for the testing (thks for the work!), cargo failed build at:

```
checking number of significant virtual address bits... error

  --- stderr
  configure: error: cannot determine number of significant virtual address bits
  thread 'main' panicked at 'command did not execute successfully: "sh" "/local/home/.../build/private/cb-coverage-target/debug/build/jemalloc-sys-c23428cb3131d9cd/out/jemalloc/configure" "--disable-cxx" "--with-jemalloc-prefix=_rjem_" "--with-private-namespace=_rjem_" "--host=x86_64-unknown-linux-gnu" "--build=x86_64-unknown-linux-gnu" "--prefix=/local/home/.../build/private/cb-coverage-target/debug/build/jemalloc-sys-c23428cb3131d9cd/out"
  expected success, got: exit status: 1', /local/home/.../build/private/cargo-home/registry/src/-1444c62b569c601a/jemalloc-sys-0.3.2/build.rs:392:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
Error: with-coverage

Caused by:
    cargo exited with status exit status: 101
```
My host type is `x86_64-unknown-linux-gnu` which is supported per: https://github.com/gnzlbg/jemallocator#platform-support.

After checking jemalloc doc, the error is thrown is at: 
https://github.com/gnzlbg/jemallocator/blob/master/jemalloc-sys/build.rs#L330

but Im not sure why the cmd is triggering the failure. 

I also tried with following this thread https://github.com/gnzlbg/jemallocator/issues/148 which does not help in my case.

Any hints pls?

**Comment by di-otter** [comment]
Also I open an issue in jemalloc repo: https://github.com/gnzlbg/jemallocator/issues/175#issue-1256802339

**Comment by henil** [comment]
Looks like jmalloc compiled successfully but one of the test is failing. Probably something related to your system configuration.

I am not familiar with jemalloc's build system but looks like its coming from https://github.com/jemalloc/jemalloc/blob/61efbda7098de6fe64c362d309824864308c36d4/configure.ac#L416-L435

But in any case I dont think issue is related to rumqtt.

**Comment by di-otter** [comment]
Thks Henil

After deep diving the building system, find that when compiling with flag `c17`, it will fail the building when running configure script since keyword `asm` is disabled by the flag but used in the script. the mix is change flag from `c17` to `gnu17` for the compilation
