### ISSUE TITLE
rumqttd - getting other events besides messages

### ISSUE THREAD

**Issue by Evanfeenstra** [bytebeamio/rumqtt#407]
Is there a way to get events such as client connects and disconnects from within rumqttd?

`let (mut tx, mut rx) = builder.connect("localclient", 200).await.unwrap();` is very nice for receiving actual messages, but it would be great to be able to subscribe to other MQTT events. Maybe all I am asking for is a more fleshed-out example of rumqttd.

Thanks a lot, this project is awesome!

**Comment by de-sh** [comment]
Are you looking for the ability to capture all Notifications and process it by yourself? i.e. [`AsyncLinkRx.link_rx.recv()`](https://github.com/bytebeamio/rumqtt/blob/master/rumqttd/src/async_locallink.rs#L75)

**Comment by Evanfeenstra** [comment]
Thanks for the tip @de-sh!

What I really meant to ask: Is there a way to subscribe to metrics from the broker? So i could respond to Connect and Disconnect events from ALL connected clients

**Comment by tekjar** [comment]
@Evanfeenstra We have something like this implemented in our private broker. We are planning to opensource it but there's no concrete timeline yet

**Comment by Evanfeenstra** [comment]
ooooooo cant wait for that! i figured it out by polling the router with a MetricsRequest.. but it could be much better

**Comment by de-sh** [comment]
@Evanfeenstra closing this issue as the project mentioned by @tekjar is expected to release ~August 15. Please open an issue there if further discussion is required.
