### ISSUE TITLE
Looks like it does not compile on Windows 10 

### ISSUE THREAD

**Issue by denis-papin** [bytebeamio/rumqtt#423]
When I try to compile the provided example on Windows 10, I run into a compilation error related to tokio 1.17.0
I use Rust 1.62.1 (stable) .

```
error[E0308]: mismatched types
    --> C:\Users\denis\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.17.0\src\net\windows\named_pipe.rs:2142:42
     |
2142 |         NamedPipeClient::from_raw_handle(h)
     |                                          ^ expected enum `std::ffi::c_void`, found enum `winapi::ctypes::c_void`
     |
     = note: expected raw pointer `*mut std::ffi::c_void`
                found raw pointer `*mut winapi::ctypes::c_void`
```

**Comment by henil** [comment]
Looks related to https://github.com/tokio-rs/tokio/issues/4662, can you try doing the suggested change there and see if it fixes this issue for you?

**Comment by de-sh** [comment]
Hi @denis-papin, have you been able to fix this issue or are you still stuck with it? Please provide as mush detail as possible.

**Comment by de-sh** [comment]
Closing this issues as deemed fixed, please reopen if you have more questions @denis-papin
