### ISSUE TITLE
Add ability to get events through polling, not only through an iterator.

### ISSUE THREAD

**Issue by SirVer** [bytebeamio/rumqtt#430]
Hey, thanks for the crate! Very useful indeed and I had very little issues with using it so far. I only use the sync interface, so I am talking about this below.

However, what would be useful for me is to get a polling interface, similar to [`std::sync::mspc::Receiver::try_recv`](https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.try_recv). Currently, all I can do to drive the event loop is calling `Connection.iter`. Quite often though, I have multiple places I receive data from: for example in some of my tools, I have a global bool that is set when it is time to clean up. In others, I also recv messages from other threads. Right now, I have to wait for the next mqtt signal to act on it, since the iter is blocking on action on mqtt - which complicates my designs significantly.

I do understand the implications that `try_recv` would need to be called regularly to keep the mqtt loop healthy, but that seems a fine interface ask to me still. Could you take this into consideration?

**Comment by tekjar** [comment]
@SirVer We'll take this into consideration in the current design

**Comment by de-sh** [comment]
> Hey, thanks for the crate! Very useful indeed and I had very little issues with using it so far. I only use the sync interface, so I am talking about this below.
> ...

Thank you for your inputs. Module v5 is heavily experimental at the moment. Please do not use it in production as there are possible holes(we are yet to fully test and verify our implementation), we are working out the proper way to do this and it seems like a `try_next()` that returns an Empty error is what you are pointing towards? Again, thanks for your input, will open a PR to resolve this by the weekend.

**Comment by SirVer** [comment]
yes. That is what I mean. It would make it possible to combine events from other sources than just mqtt which is a common pattern in my use cases. 

I’ll post an example that currently is hard later.

**Comment by SirVer** [comment]
Here is a motivating example in code. The aim here is to replace this "poor mans logging" commandline: ```mosquitto_sub -v -t "topic/of/interest"  | tee -a /srv/log/mqtt_logger.log```.

Essentially, we listen to one or more topics, and every topic received we write into a `logfile`. since the logfile is buffered and we only want complete messages in the file, we want to ensure that upon termination of the program the buffer is flushed. One way of doing so is shown below: We register a `ctrl-c` handler which sends a message to a channel. The main thread needs to terminate if this channel has a message. The code below is functional, however due to the iterator interface of rumqtt the program will only terminate upon the next event received after a ctrl-c. Some topics only see a message once per hour, so this is very unpractical.

```rust
fn main() -> Result<()> {
    let (tx, rx) = channel();

    // We set a handler for Ctrl-c, mainly so that if the process is interrupted, the 'logfile'
    // below is correctly dropped and hence flushes its buffers to disk.
    ctrlc::set_handler(move || {
        // We ignore the send error, this only means that our receiver is already dropped, hence
        // the main thread has terminate.
        let _ = tx.send(());
    })
    .expect("setting Ctrl-C handler always works.");

    let mut logfile = BufWriter::new(fs::File::create(p)?);
    'outer: loop {
        let mut mqttoptions =
            MqttOptions::new("mqtt_logger", "localhost", 1883);
        let (mut client, mut connection) = Client::new(mqttoptions, 10);
        client.subscribe("/topic/of/interest", QoS::ExactlyOnce)?;

        use rumqttc::Event::*;
        use rumqttc::Packet::*;
        for notification in connection.iter() {
            match rx.try_recv() {
                Ok(_) => break 'outer,
                Err(TryRecvError::Empty) => (),
                Err(TryRecvError::Disconnected) => unreachable!("nothing can drop the sender"),
            };
            match notification.unwrap() {
                Incoming(Publish(data)) => {
                    handle_message(&data.topic, &data.payload, &mut logfile
                }
                Incoming(_) | Outgoing(_) => Ok(()),
            };
        }
    }
    Ok(())
}
```

The following code is pseudo, but this is rather how I'd like the main loop to look:

```rust
'outer: loop {
    let mut mqttoptions = MqttOptions::new("mqtt_logger", "localhost", 1883);
    let (mut client, mut connection) = Client::new(mqttoptions, 10);
    client.subscribe("/topic/of/interest", QoS::ExactlyOnce)?;

    use rumqttc::Event::*;
    use rumqttc::Packet::*;
    const SLEEP_TIME_MS: i32 = 100;
    loop {
        let now = Instant::now();
        match rx.try_recv() {
            Ok(_) => break 'outer,
            Err(TryRecvError::Empty) => (),
            Err(TryRecvError::Disconnected) => unreachable!("nothing can drop the sender"),
        };

        loop {
            match connection.try_recv() {
                Ok(Incoming(Publish(data))) => {
                    handle_message(&data.topic, &data.payload, &mut logfile);
                }
                Err(TryRecvError::Empty) => break,
                Err(e) => todo!("Handle error!"),
            }
        }
        thread::sleep(Duration::from_millis(max(0, SLEEP_TIME_MS - elapsed) as u64));
    }
}
```

This gives much more control over reaction speed and fanning in different sources of events.

**Comment by de-sh** [comment]
> This gives much more control over reaction speed and fanning in different sources of events.

Understood, what do you think about the PR?

**Comment by SirVer** [comment]
@de-sh I reviewe the MR, it seems like a clean interface that does what I want. I left some more opinionated comments, feel free to disregard.

This seems to touch the never version of this crate (is it v5?). Can we get a similar path to the existing version of the crate? Or is v5 ready for prime time soon?

**Comment by de-sh** [comment]
> This seems to touch the never version of this crate (is it v5?). Can we get a similar path to the existing version of the crate? Or is v5 ready for prime time soon?

**Comment by de-sh** [comment]
> Can we get a similar path to the existing version of the crate? Or is v5 ready for prime time soon?

v5 will take some time to stabilize, in the meanwhile, [would this be something that you're asking for](https://github.com/bytebeamio/rumqtt/compare/non-blocking?expand=1#diff-37ee311781ea8c2245bed9c527bf807ac9b54c5989124635eb6effc02fcb7ec1R396-R442)?

**Comment by SirVer** [comment]
@de-sh Super late reply, sorry for that. Yes, this is exactly what I'd like to have, I am craving for the `recv_timeout` call which would simplify my use cases tremendously.

**Comment by SirVer** [comment]
@de-sh When will the v3 try_recv branch be merged? Still eagerly awaiting it!

**Comment by de-sh** [comment]
> @de-sh When will the v3 try_recv branch be merged? Still eagerly awaiting it!

We are still brainstorming ways to do this, the problem we face is with how `EventLoop::poll()` works, we are unsure if adding dependency on futures is the right way to go about this.
