### ISSUE TITLE
parse_url does not handle ssl/tls like document implies

### ISSUE THREAD

**Issue by Jimmy-Z** [bytebeamio/rumqtt#435]
The document says:
> NOTE: A url must be prefixed with one of either tcp://, mqtt://, ssl://,mqtts://, ws:// or wss:// to denote the protocol for establishing a connection with the broker.

https://docs.rs/rumqttc/0.14.0/rumqttc/struct.MqttOptions.html#method.parse_url

While `"mqtts" | "ssl"` is simply not handled:
https://github.com/bytebeamio/rumqtt/blob/2f11546b64d4ab86b2b49642d8b7068f624992a9/rumqttc/src/lib.rs#L611-L620
similar to #434 

At least the document should be updated to prevent confusion.

**Comment by de-sh** [comment]
Hey @Jimmy-Z, thanks for the pointer. Have opened a PR, can you verify if the changes are good to go?

**Comment by Jimmy-Z** [comment]
Looks fine to me.

**Comment by de-sh** [comment]
Have updated default behavior to use native-certs
