### ISSUE TITLE
Does new ng broker support username and password?

### ISSUE THREAD

**Issue by msdrigg** [bytebeamio/rumqtt#469]
I can't find how to specify the username and password in the new config.

**Comment by msdrigg** [comment]
I can't find how to specify the username and password in the new config.

**Comment by elasticdotventures** [comment]
Also looking for howt specify username and password?

**Comment by henil** [comment]
this was recently implemented (in https://github.com/bytebeamio/rumqtt/pull/553) and released (in `rumqttd 0.12.2`). 

you can specify map of username and password that are allowed to connect in config file in either of 2 ways as shown in the new config file: https://github.com/bytebeamio/rumqtt/blob/726b26367d936c963cc8e1cc25358003c6586812/rumqttd/rumqttd.toml#L27-L30

Also do note that this username and password will be send in plain text by client when using normal TCP connection, so it is recommended to use this over encrypted channel like TLS.
