### ISSUE TITLE
Why does rumqttd not allow topic prefixes that start with "test" or "$"?

### ISSUE THREAD

**Issue by ethanholz** [bytebeamio/rumqtt#479]
The router for this project throws an error when a topic prefix begins with "test' or "$", I was just wondering why this decision was made? Blocking the "$" prefix breaks compatibility with certain tools such as MQTT Explorer which by default subscribes to "$SYS/#".  I

Great work on this project so far, any insight would be appreciated!

**Comment by henil** [comment]
not sure about `test` but related to `$`.

 As we are not publishing any metrics related to broker on `$SYS` topics we are currently not differentiating between topics that start with `$` and ones that doesn't, which is required by [spec](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718108) (so if it was allowed one would get messages published on topics prefix with `$` if there was subscription on `#`).

**Comment by ethanholz** [comment]
Thanks for the explanation! As for `test`, it looks like this is due to the test topic being used for testing internally. This is referenced [here](https://github.com/bytebeamio/rumqtt/blob/eca0929a67309f3424e21993f526b4b646de67a2/rumqttd/src/router/routing.rs#L1181-L1186) in routing.rs. Would this project be open to modifying this (and any associated testing) to allow for users to use that topic?

**Comment by henil** [comment]
Yeah you are write, we are using it [here](https://github.com/bytebeamio/mqttwrk/blob/master/src/conformance/basic.rs#L737-L754). which is a port of paho conformance [test suite](https://github.com/eclipse/paho.mqtt.testing/blob/master/interoperability/client_test.py#L350-L367). So we just need a topic that gives a negative response for a subscribe packet.

We can probably change that to `donotsubscribetothistopic`. Any suggestion for better name of the topic?

**Comment by ethanholz** [comment]
I don't think it really matters so long as it is documented. Maybe adding a prefix like `rumqtt-donotsubscribetothistopic`. The alternative could be modifying the conformance test to fail on `$` instead as since this is not in spec, we should expect this to fail for brokers.
