### ISSUE TITLE
Infinite ping issue

### ISSUE THREAD

**Issue by EnricoMucelli** [bytebeamio/rumqtt#486]
when i publish something in my topic it works but then it won't continue with the rest of the program, instead it's stucked in this infinite loop of
Notification = Ok(Outgoing(PingReq))
Notification = Ok(Incoming(PingResp))

the publisher is in a for loop so i need that when the message is published the program continues to run.

rumqtt code:

        use rumqttc::{MqttOptions, Client, QoS};
        use serde_json::Value;
        use std::time::Duration;
        use std::thread;
        
            
            pub fn run_mqtt(info:Value){
        
                let mut mqttoptions = MqttOptions::new("n", "test.mosquitto.org", 1883);
                //mqttoptions.set_credentials("nos", "$.NosTest.$");
                mqttoptions.set_keep_alive(Duration::from_secs(5));
                let (mut client, mut connection) = Client::new(mqttoptions, 1000);
                client.subscribe("topic1", QoS::AtMostOnce).unwrap();
                thread::spawn(move || {
                client.publish("topic1", QoS::AtLeastOnce, false, serde_json::ser::to_vec(&info).unwrap()).unwrap();
                thread::sleep(Duration::from_millis(100));
                });
        
                for (i, notification) in connection.iter().enumerate() {
                println!("{}. Notification = {:?}", i, notification);
                }
                
            }

**Comment by de-sh** [comment]
I tested the provided code and don't seem to face any issues:
```
0. Notification = Ok(Incoming(ConnAck(ConnAck { session_present: false, code: Success })))
1. Notification = Ok(Outgoing(Subscribe(1)))
2. Notification = Ok(Outgoing(Publish(2)))
3. Notification = Ok(Incoming(SubAck(SubAck { pkid: 1, return_codes: [Success(AtMostOnce)] })))
4. Notification = Ok(Incoming(Publish(Topic = topic1, Qos = AtMostOnce, Retain = false, Pkid = 0, Payload Size = 13)))
5. Notification = Ok(Incoming(PubAck(PubAck { pkid: 2 })))
6. Notification = Ok(Outgoing(PingReq))
7. Notification = Ok(Incoming(PingResp))
8. Notification = Ok(Outgoing(PingReq))
```

**Comment by EnricoMucelli** [comment]
i don

> The right way to do this would be to wait for the Publish acknowledgement instead of doing a for loop on `connection.iter()`

can you show me please?

**Comment by de-sh** [comment]
Just change the for loop to the following in this case:
```rust
for (i, notification) in connection.iter().enumerate() {
    println!("{}. Notification = {:?}", i, notification);
    if let Ok(Event::Incoming(PubAck(_))) = notification {
        break
    }
}
```

**Comment by EnricoMucelli** [comment]
> Just change the for loop to the following in this case:
> 
> ```rust
> for (i, notification) in connection.iter().enumerate() {
>     println!("{}. Notification = {:?}", i, notification);
>     if let Ok(Event::Incoming(PubAck(_))) = notification {
>         break
>     }
> }
> ```
> 
> This works here since we aren't really considering what the pkid is for the publish packet

![error](https://user-images.githubusercontent.com/115789270/196701296-b6a3df1a-fab6-4056-9b1a-72e2ac52d8fb.png)

**Comment by EnricoMucelli** [comment]
> 

IT WORKS THANK YOU A LOT YOU SAVED ME
