### ISSUE TITLE
Include printing of payload in examples

### ISSUE THREAD

**Issue by Arend-Jan** [bytebeamio/rumqtt#509]
In the examples the "state" of the received message is printed. It would be great to include printing of the payload of the received message as well.

**Comment by stuart-haas** [comment]
@Arend-Jan I had to do some digging to figure this out for myself. There are some additional sample not listed on the doc site for async manual ack. I took that example as well as some additional research to come up with implementation.

Checkout [MQTT Protocol Message Overview](http://www.steves-internet-guide.com/mqtt-protocol-messages-overview/) and go to the section called MQTT Control Field Structure. Here's a sample as well that will print out the raw bytes from the payload as utf-8. Essentially this can just replace the `loop` that is used in the async pub/sub example.

```
    loop {
        match event_loop.poll().await {
            Ok(event) => {
                println!("Event = {:?}", event);
                if let Event::Incoming(packet) = event.clone() {
                    if let Packet::Publish(publish) = packet {
                        println!("Payload = {:?}", String::from_utf8_lossy(&publish.payload));
                    }
                }
                Ok(event)
            },
            Err(err) => {
                println!("ConnectionError = {:?}", err);
                Err(err)
            }
        };
    }
```

**Comment by Arend-Jan** [comment]
Do you want me to create pull request for this?

**Comment by de-sh** [comment]
> Do you want me to create pull request for this?

Yes please, we have not included this in the examples because payload serialization is upto the user of the library. The only guarantee made by rumqttc is that the bytes provided by the user application will be packed into an appropriate MQTT packet and transported to a broker, vice versa.

**Comment by henil** [comment]
Hey @Arend-Jan we wouldn't like to include payload content by default in our examples because it would make it hard to see what other events we got.

Incase you want to see it you can just add a println similar to what mentioned in example by @stuart-haas.

Feel free to reopen if you have more questions.
