### ISSUE TITLE
How do I abort the main loop?

### ISSUE THREAD

**Issue by vpopescu** [bytebeamio/rumqtt#513]
This  may be a stupid question, but looking through the examples and other github implementations, I couldn't find a good approach.

What is the idiomatic way to abort the main event loop immediately and cleanly? 
e.g. from your example:

```
 loop {
        // get subscribed messages without acking
        let event = eventloop.poll().await;
        println!("{:?}", event);
        if let Err(_err) = event {
            // break loop on disconnection
            break;
        }
    }
```
how can I abort this loop while it's waiting in eventloop.poll().await? I would like to abort it in such a way that either I get a chance to send a disconnect() or rumqtt sends the disconnect for me. I don't want to wait for the KeepAlive timeout.

**Comment by de-sh** [comment]
You can use a cancellation channel for this:
```rust
let (cancel_tx, cancel_rx) = bounded(1);
loop {
  tokio::select!{
    event = eventloop.poll() => {
      println!("{:?}", event);
      if let Err(_err) = event {
        // break loop on disconnection
        break;
      }
    }
  }
}
```

**Comment by vpopescu** [comment]
That works, and I had something similar, however my problem was that I'm trying to implement a reconnect with retry backoff in the poll handler.  So in effect, I ended up with something like this:

```
let (cancel_tx, cancel_rx) = flume::bounded(1);
loop {
  tokio::select!{
    _ = cancel_rx.recv_async() {
      // break loop on recv of cancel
      break;
    }
    event = eventloop.poll() => {
      println!("{:?}", event);

     // protcode if it'a reconnectable error, like ConnectionError
     if (_err == ConnectionError) {
         tokio::time::sleep(get_current_backoff());
         continue;
      }
     else {
        break;
    }
    }
  }
}
```

The problem is that with this code, if I use you recommendation, and I'm in an exponential backoff of say, 1 minute, the cancelation won't be processed until that time expires (since it holds that branch from completing)

Maybe I should do the exponential backoff a different way?
