### ISSUE TITLE
Client loop hangs and never returns any data

### ISSUE THREAD

**Issue by SirVer** [bytebeamio/rumqtt#525]
sorry, I pressed return too quickly:

I have the following code running on ~400 IoT devices in the field:

```
fn main() -> Result<()> {
    let args = Args::parse();

    'outer: loop {
        let mut mqttoptions = MqttOptions::new("parking_sensor", &args.hostname, args.port);
        mqttoptions.set_keep_alive(std::time::Duration::from_secs(60));

        let (mut client, mut connection) = Client::new(mqttoptions, 10);
        client.subscribe(SUB_TOPIC_RAW_SIGNAL, QoS::AtLeastOnce)?;

        use rumqttc::Event::*;
        use rumqttc::Packet::*;
        let mut last_seen_data = time::Instant::now();
        loop {
            if last_seen_data.elapsed() > time::Duration::from_secs(15) {
                eprint!("Haven't seen new data for > 15seconds. Reconnecting.");
                continue 'outer;
            }

            let notification = match connection.recv_timeout(std::time::Duration::from_millis(50)) {
                Ok(v) => v,
                Err(RecvTimeoutError::Disconnected) => {
                    eprintln!("client disconnected. Reconnecting.");
                    continue 'outer;
                }
                Err(RecvTimeoutError::Timeout) => continue,
            };

            let n = match notification {
                Ok(n) => n,
                Err(e) => {
                    eprintln!("MQTT error. Will reconnect: {e}.");
                    break;
                }
            };
            let res = match n {
                Incoming(Publish(data)) => match &data.topic as &str {
                    SUB_TOPIC_RAW_SIGNAL => {
                        last_seen_data = time::Instant::now();
                        // Not of concern to this example
                    }
                    _ => unreachable!("We never subscribe to other topics"),
                },
                Incoming(_) | Outgoing(_) => Ok(()),
            };

            if let Err(e) = res {
                eprintln!("error in handle_raw_signal. Will reconnect: {e}.");
                break;
            }
        }
    }
}
```

I had the same code prior without the `revc_timeout` and instead using the iteration example from the landing page of this repo. The `SUB_TOPIC_RAW_SIGNAL` receives ~1-1.5kB of data at 1Hz rate. This I can verify using `mosquitto_sub`.

however, my program hangs: it prints every 15 second the `eprint!` statement, and even though it fully recreates the client, it still does not see the data. This happens at least once or twice per day on any one of the machine. Killing and restarting the program helps

My hunch is that something in the underlying async code has a rare race condition, but i have no way of knowing.

**Comment by SirVer** [comment]
@tekjar @de-sh Sorry for sending an empty bug report initially. I think I found a pretty big problem in the underlying library - I will need to pull it out of production, because of this :(.

Maybe you have an idea what could cause this?

**Comment by tekjar** [comment]
@SirVer Would it help if we setup a private call to discuss how we better solve this faster?

**Comment by SirVer** [comment]
@tekjar that would be greatly appreciated. I am in Munich time zone, my work email is holger@qwello.eu.

**Comment by tekjar** [comment]
@SirVer I've sent you a mail. Please check you spam as well

**Comment by tekjar** [comment]
Also if the above is a minimal viable example to reproduce the bug, can you also update `last_seen_data` after receiving an incoming publish (or else you'll see the message in eprint!)

**Comment by SirVer** [comment]
@tekjar I accidentally removed the update of `last_seen_data` when cutting down code to make the example minimal viable. I edited the first post now to add it back where it was. Sorry for the confusion.

**Comment by SirVer** [comment]
After exemplary debugging help from @tekjar et al in private email threads and on video chats, we contained our problem now successfully. For posterity to everybody stumpling upon this:

There is a chance of deadlock in publishing if you use subscription (i.e. querying the main mqtt loop, either through `Connection::iter` or through polling on the connection via `recv_timeout) and publishing (through `Client::publish`) on the same thread. It is advised to have two threads always and send data from the receiving thread to the publishing thread via a `mpsc::channel`. The API does make it easy to make this mistake at this point in time though which I would still consider a bug.

@tekjar your call if you want to close this or leave it open. I am unblocked for the moment though.
