### ISSUE TITLE
Perform a healthcheck

### ISSUE THREAD

**Issue by StephenWakely** [bytebeamio/rumqtt#562]
Is there a way, or would it be possible to create a way to perform a healthcheck against an MQTT server? 

We'd like to be able to verify as early as possible whether there are any connection issues to the server before we start sending events to it.

I'm thinking this would be a function on `Client` or `AsyncClient` that just creates an `EventLoop`, verifies it can connect and ideally perform a Ping. Any error on this process would be reported back.

**Comment by tekjar** [comment]
@StephenWakely You want to verify if connection and pings to the broker are successful before starting to send events?

**Comment by StephenWakely** [comment]
> @StephenWakely You want to verify if connection and pings to the broker are successful before starting to send events?

Correct. We are using this library in [Vector](https://vector.dev). When Vector starts up it trying to ensure as much as possible that any systems it connects to are healthy. This way the user can handle any issues right away rather than wait until a message actually needs to be sent.

**Comment by tekjar** [comment]
You can [eventlooop.poll](https://docs.rs/rumqttc/latest/rumqttc/struct.EventLoop.html#method.poll) and wait on connack (incoming event)[https://docs.rs/rumqttc/latest/rumqttc/struct.EventLoop.html#method.poll] to validate the connection.

Eventloop will also send ping requests automatically based on your configuration. You can wait for ping responses

https://github.com/bytebeamio/rumqtt/blob/main/rumqttc/examples/asyncpubsub.rs#L21-L33

Let me know if you need a much more concrete example.

**Comment by henil** [comment]
Feel free to reopen if you have any more questions.
