### ISSUE TITLE
API docs? examples? specs? integration tests?

### ISSUE THREAD

**Issue by costa** [bytebeamio/rumqtt#58]
Hello, thanks for your effort.
I can't seem to find any of the subj.
I'm considering using this (or alternatives) for simple embedded MQTT client-server communication.

**Comment by tekjar** [comment]
Embedded as in embedded with OS or bare metal?

**Comment by costa** [comment]
Embedded as in-process — building a tiny pre-auth MQTT bridge to... NATS at the moment.

**Comment by tekjar** [comment]
https://docs.rs/rumq-client/0.1.0-alpha.9/rumq_client
https://github.com/tekjar/rumq/tree/master/rumq-client/examples

**Comment by costa** [comment]
@tekjar Thank you, but the client is of less concern, there's a pretty lot of client implementations for Rust etc, I'm looking for an elaborate broker library, so I can manage sockets by myself and have callbacks for a subset of protocol events, e.g. a client sends `subscribe` and I want to reply with a `deny` if it fails some custom application logic or `accept` otherwise.

**Comment by tekjar** [comment]
Ahh..Sorry the broker is not ready yet. We are working on a distributed broker in a private repo. There is a basic version in `rumq-broker` folder which doesn't have much documentation

See this for basic usage

https://github.com/tekjar/rumq/blob/master/rumq-cli/src/main.rs

**Comment by tekjar** [comment]
There is an alpha release of broker. Feel free to reopen this if you are still interested
