### ISSUE TITLE
v5 incoming event is boxed?

### ISSUE THREAD

**Issue by dberlin** [bytebeamio/rumqtt#581]
So in the non-v5 client, he Event struct has a stack allocated Incoming, Outgoing.
In v5, Incoming (but not Outgoing) is boxed.

This makes pattern matching the incoming event in v5 more annoying (and incompatible with the non-v5 one) , because box patterns are not available (and will never be, it looks like rust will try to stabilize deref patterns instead).
As a result, you have to split the match.

IE in non-v5 you can have a match arm of Event::Incoming(Incoming::ConnAck(ack)) 
in v5, you can't, because it would have to be Event::Incoming(box Incoming::ConnAck(ack))

As far as i can tell, there is no totally obvious reason why Incoming is boxed in v5.
Removing the box and updating 3 lines of code to not use boxing still passes all tests, and works fine in my (admittedly simple) app.

Is there a particular reason it's boxed?
If not, i'll send along a pull request to unbox it.

**Comment by de-sh** [comment]
@dberlin this seems to have been my bad, an unnecessary premature optimization that actually did little to no good. Have opened a PR to revert.

**Comment by dberlin** [comment]
Awesome, thank you!
