### ISSUE TITLE
Please transfer ownership of old rumqtt repo

### ISSUE THREAD

**Issue by bestouff** [bytebeamio/rumqtt#59]
Hi,

Thank you for your hard work. I still have projects using the old `rumqtt` and would like to (very) passively maintain it (e.g. bump some dependencies, apply a few trivial merge requests).  
Would it be possible for you to transfer ownership of the github repo and the crate to me ?

**Comment by tekjar** [comment]
Hi @bestouff. I wouldn't have created this repo if that was possible. I asked my ex employer to transfer the ownership to me as they didn't have enough workforce to maintain it and I did not get a positive response

We have 2 options. Fork and maintain it or add a similar high level layer that matches rumqtt on top of this repo

**Comment by bestouff** [comment]
Oh right. How about the [crate](https://crates.io/crates/rumqtt) ownership ? Same problem ?

**Comment by tekjar** [comment]
@bestouff Crates account is under my ownership but not sure of other legalities. Most probably not a problem

**Comment by bestouff** [comment]
So could you point the crates repo to a fork of `rumqtt` ? Either one you do, or one I do, as you prefer. I'm notoriously bad at finding free time to maintain my stuff but I can find a few minutes to apply some merge requests if needs be.

**Comment by tekjar** [comment]
Yeah I'm thinking of a few options here

Rename this repo to `rumqtt` and provide similar higher level methods as rumqtt and push to existing crates.io (probably as 1.0) and make you a maintainer of the client. Will that work for you? I'm focusing mostly on the broker these days. It would be good to have some help w.r.t ownership and maintenance of the client

**Comment by bestouff** [comment]
Seems like a good idea.
> I'm notoriously bad at finding free time to maintain my stuff  

However my first aim is really to have the original `rumqtt` to still exist and enter passive maintenance mode (no break, no new features, just a few patches), to offer a low-cost solution for existing projects without migration.

**Comment by bestouff** [comment]
... and as a second, step, why not creating an `rumqtt_compat` crate offering a layer above `rumq` (for client mode), which would be used like this:
```rust
use rumqtt_compat as rumqtt;
```

**Comment by bestouff** [comment]
Apparently things happened to this repo. Would it be possible to know what ?

**Comment by tekjar** [comment]
This library now supports both synchronous and async versions

**Comment by bestouff** [comment]
Oh my bad, I thought this bug was opened on the old repo. No news on that front then.

**Comment by tekjar** [comment]
Yeah I don't have control of that repo. But you can probably migrate to this I guess. That way I can support you better

**Comment by tekjar** [comment]
I think there isn't anything actionable w.r.t to old repo. Coming to 'rumqtt' in crates, I'll probably use it as a command line utility. rumqttc has both sync and async support if you want to migrate
