### ISSUE TITLE
No further events after getting "payload size limit exceeded" error

### ISSUE THREAD

**Issue by hachmeister** [bytebeamio/rumqtt#614]
# Expected Behavior

Getting further events after the error "payload size limit exceeded" occurs.

# Current Behavior

I don't get any events after the error "payload size limit exceeded".

# Failure Information (for bugs)

* Operating System: Linux Debian Bookworm
* Toolchain version: rustc 1.69.0 (84c898d65 2023-04-16)
* rumqttc version: 0.20.0

## Failure Logs

```
Error: Mqtt state: Mqtt serialization/deserialization error: payload size limit exceeded: 65555
```

The following is the slightly changed example from the github site which gives me an error, if I try to recieve packages bigger than the `max_incoming_packet_size`, but after that there are no more events.

```
use std::thread;
use std::time::Duration;
use rumqttc::{Client, Event, Incoming, MqttOptions, QoS};

fn main() {
    let mut mqttoptions = MqttOptions::new("rumqtt-sync", "localhost", 1883);
    mqttoptions.set_keep_alive(Duration::from_secs(5));
    mqttoptions.set_max_packet_size(10 * 1024, 128 * 1024);

    let (mut client, mut connection) = Client::new(mqttoptions, 10);
    client.subscribe("hello/rumqtt/#", QoS::AtMostOnce).unwrap();
    thread::spawn(move || {
        [10, 128, 256, 65535, 256, 128, 10].iter().for_each(|count| {
            let result = client.publish("hello/rumqtt/short", QoS::AtLeastOnce, false,
                                          vec![1; *count as usize]);
            match result {
                Ok(_) => {},
                Err(e) => println!("Error: {e}"),
            }
        });
    });

    for (_i, notification) in connection.iter().enumerate() {
        match notification {
            Ok(event) => {
                match event {
                    Event::Incoming(Incoming::Publish(publish)) => {
                        println!("Publish: {publish:?}")
                    }
                    _ => {}
                }
            }
            Err(e) => {
                println!("Error: {e}")
            }
        }
    }
}

```

I can understand that I can't recieve a package that exceeds the `max_incoming_packet_size`, but after that the smaller packages are not recieved also.

**Comment by de-sh** [comment]
I believe the problem here is that once we face an error, we disconnect from the broker and lose any related subscriptions as `clean_session: true` means we are using a non-persistent connection, please try out the following change:
```
+ mqttoptions.set_clean_session(false);
```

**Comment by hachmeister** [comment]
Yes, the error repeats with `clean_session` set to `false`.

I wonder how it is meant to use this notification loop when encountering errors.

Maybe it should be possible to skip a message if it cannot be processed.

Another idea would be to make the stream for the payload available to the user, so that he can decide for himself how and whether this message is processed.

**Comment by tekjar** [comment]
@hachmeister If you `continue` to loop after encountering an error, rumqttc will reconnect to the broker.  The behaviour you are seeing is expected. 

- If `clean_session = true`, broker will forget the subscription and not send publishes after reconnection
- If `clean_session = false`, broker will keep retransmitting the problematic packet and client will keep disconnecting

It not possible to skip a problematic message and read the next packet because of the way tcp works. Skipping a problematic message (and processing the next message) in userspace requires reading all the data of bad message from network and dropping it. This is a security risk. 

The ideal way to deal with this problem is to have correct configuration on the broker (where broker should not send bad messages to the client)

**Comment by hachmeister** [comment]
@yatinmaan I am using eclipse mosquitto in a local docker container for testing purposes.

I used a minimal config:

```
listener 1883
allow_anonymous true
```
and started it with:

```
docker run --rm -p 1883:1883 -v $PWD/mosquitto:/mosquitto eclipse-mosquitto:2.0.15
```

@tekjar If I cannot skip a message, I think the only way is to limit the `max_package_size` from the mqtt broker und use the same limit with the client.

Is that what you mean with the "ideal way"?

Just because the message is big, it is not necessarily bad.

**Comment by tekjar** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> @tekjar If I cannot skip a message, I think the only way is to limit the `max_package_size` from the mqtt broker und use the same limit with the client.
> 
> 
> Is that what you mean with the "ideal way"?

Yeah. There should be some form of config synchronization between broker and client 



> Just because the message is big, it is not necessarily bad.

Bad in the context of client configuration
