### ISSUE TITLE
Please Update Image on DockerHub

### ISSUE THREAD

**Issue by tomtom215** [bytebeamio/rumqtt#629]
# Expected Behavior

Latest tag on DockerHub pulls the current release available on GitHub

# Current Behavior

Latest tag on DockerHub pulls an 8 month old image:

    version: 0.12.0-beta.1
    profile: release
    commit_sha: b1e6b6609c0e6a7dd73c54ded69613c0ced75de5
    commit_date: 2022-09-30T13:52:02Z

**Comment by swanandx** [comment]
Hey, thank you for letting us know! We will update the image 💯

**Comment by swanandx** [comment]
please checkout the updated latest [image](https://hub.docker.com/layers/bytebeamio/rumqttd/latest/images/sha256-3a49e297a24934877161e1986c00bf12f04cb7ee932ce9ca67c5227b59292499?context=repo) ! Thank you 😁

**Comment by henil** [comment]
we have also updated the README, which more detailed explanation related to how to start the broker with a custom configuration file. 

which looks like is part of the issue in #630.
