### ISSUE TITLE
Keep Alive has an arbitrary limit

### ISSUE THREAD

**Issue by danieldougherty** [bytebeamio/rumqtt#643]
# Expected Behavior

According to both MQTT specs, the Keep Alive value should be an integer from 0 to 65,535. A non-zero value indicates the number of seconds between messages before the client must send a pingreq; a value of 0 disables the keep-alive mechanism.

# Current Behavior

Attempting to set a keep-alive value of less than 5 seconds fails with the output 'Keep alives should be >= 5 secs'. This makes it impossible to set a 0 value, or to use shorter intervals for testing/time-sensitive applications.

**Comment by henil** [comment]
currently [pings are sent](https://github.com/bytebeamio/rumqtt/blob/714f71c9bc3369fa186353201dc2e8197d07594c/rumqttc/src/eventloop.rs#L228-L240) regardless of if there is activity on the network or not. 

So to avoid user from setting it something very small and generate alot of unnecessary traffic we had put that limit. Also according to spec:
> The actual value of the Keep Alive is application specific; typically this is a few minutes.

But I agree it should be `>= 1 second`.


> it impossible to set a 0 value

i think this can be implemented by disabling the `select!` branch that sends the pings (cc: @yatinmaan)

Both of this should be an easy fix, do you want to open a PR for this @danieldougherty ?
