### ISSUE TITLE
v1 release

### ISSUE THREAD

**Issue by tekjar** [bytebeamio/rumqtt#65]
Stuff to do before 1.0 release on May 1st week

mqtt4bytes
---------------
- Check if can completely remove allocations for no std 
- Finalize APIs

rumqttc
----------------
- High level channel like interface for client (spawns a thread but hides tokio)
- Finalize APIs

rumqttd
----------------
- A very basic  broker which can be embedded
- Commit log finalization
- Clustered mode tested on 3 nodes

commandline
---------------
- Some mosquitto like options
- Brew package

Related to #64

**Comment by jplatte** [comment]
What about 0.x where x >= 1, before jumping to 1.0?

**Comment by tekjar** [comment]
@jplatte We can do that right away. I'll add unsubscribe and diconnect before that
