### ISSUE TITLE
graceful exit from connection.iter() returns Err

### ISSUE THREAD

**Issue by BlackZork** [bytebeamio/rumqtt#662]
I extracted important parts from my first rust project below. This is synchrononus loop inside a worker thread, when controlling thread is supposed to end loop and exit cleanly.
```rust

use rumqttc::{MqttOptions, Client, Packet};
use rumqttc::Event;
use signal_hook::{consts::SIGTERM, iterator::Signals};

fn do_work() {
    let (mut client, mut connection) = Client::new(mqttoptions, 10);
   
    client.subscribe(...)
    let mut signals = Signals::new(&[SIGTERM]).unwrap();

    let client_arc = Arc::new(Mutex::new(client));

    let thread_client = client_arc.clone();

    let mqtt_loop = thread::spawn(move || {
        for (_i, notification) in connection.iter().enumerate() {
            trace!("Notification = {:?}", notification);
            ... some work here
            let mut client_shared = thread_client.lock().unwrap();
            client_shared.publish('some_topic', ...)
        }    
    });

    for sig in signals.forever() {
        info!("Recevied signal {:?}", sig);
        if sig == SIGTERM {
            let mut client_shared = client_arc.lock().unwrap();
            client_shared.disconnect().unwrap();
            break;
        }
    }

    debug!("Joining processing thread");
    mqtt_loop.join().unwrap(); 
}
```

# Expected Behavior

When I kill process with SIGHUP, `mqtt_loop` should end without error.

# Current Behavior

I got a notifcation with Err that peer closed a connection:

```Notification = Err(MqttState(Io(Custom { kind: ConnectionAborted, error: "connection closed by peer" })))```

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: ArchLinux
* Toolchain version: cargo 1.70.0 (ec8a8a0ca 2023-04-25)
* rumqttc = "0.17.0"

**Comment by swanandx** [comment]
When broker receives `Disconnect` packet, it will close the connection, but that connection is still open from client ( rumqttc ) end, therefore it will error out saying broker closed connection!

As per OASIS [standards](https://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718094) , client must have closed the network connection, which i think we aren't doing. 

This is same for `rumqttc = "0.22.0"` as well!

minimal example for reproducing:
```rust
use rumqttc::{self, Client, MqttOptions};
use std::thread;
use std::time::Duration;

fn main() {
    let mqttoptions = MqttOptions::new("issue-662", "localhost", 1883);

    let (client, mut connection) = Client::new(mqttoptions, 10);
    thread::spawn(move || do_work(client));

    for (i, notification) in connection.iter().enumerate() {
        match notification {
            Ok(notif) => {
                println!("{i}. Notification = {notif:?}");
            }
            Err(error) => {
                println!("{i}. Notification = {error:?}");
                return;
            }
        }
    }

    println!("Done with the stream!!");
}

fn do_work(mut client: Client) {
    thread::sleep(Duration::from_secs(1));
    client.disconnect().unwrap();
}
```

Thank you for pointing this out @BlackZork ! Let me know if you would like to contribute in fixing this :100:

**Comment by BlackZork** [comment]
I will of course test fix for this issue, but I do not think I am able to contribute to the fix with current level of my Rust knowledge ( I pasted into this issue over 30% of total code I have written in Rust so far :-) )

**Comment by swanandx** [comment]
no worries!

**Comment by swanandx** [comment]
I tried to fix it, but it has some more challenges due to design:
- we can close connection at client side, but what if that happens before broker has recv / processed the disconnect packet, it will think the connection got closed unexpectedly! ( this will be another issue to think on lol )
- after sending disconnection, what would we return as result of `poll()` / `iter().next()`?
  - if we return `Ok(Disconnect)`, our code will continue polling and thus will try to reconnect!
  - if we return `Err(_)`, it is the same effect as rn haha
 
what you can do for now is, when you get outgoing disconnect notification, stop polling the eventloop, so that you won't get into state error:

```rust
use rumqttc::{self, Client, Event, MqttOptions, Outgoing};
use std::thread;
use std::time::Duration;

fn main() {
    let mqttoptions = MqttOptions::new("issue-662", "localhost", 1883);

    let (client, mut connection) = Client::new(mqttoptions, 10);
    thread::spawn(move || do_work(client));

    for (i, notification) in connection.iter().enumerate() {
        match notification {
            Ok(Event::Outgoing(Outgoing::Disconnect)) => {
                println!("Disconnecting...");
                // timeout before return to make sure broker
                // received the Disconnect packet.
                // set the timeout duration as per your need!
                thread::sleep(Duration::from_millis(500));
                return;
            }
            Ok(notif) => {
                println!("{i}. Notification = {notif:?}");
            }
            Err(error) => {
                println!("{i}. Notification = {error:?}");
                return;
            }
        }
    }

    println!("Done with the stream!!");
}

fn do_work(mut client: Client) {
    client.disconnect().unwrap();
}
```

**Comment by BlackZork** [comment]
- client.disconnect() should first signal event loop that disconnect is pending. Event loop should go into some "Disconnecting" state.
 - then client should send Disconnect packet to broker and close socket connection
 - event loop in this Disconnecting state should wait in iter() for socket to be closed and break from for loop on iter(). Incoming packets should be dropped in this state and should not fire next iteration.

Optimally event loop could return one event  Ok(Disconnected) and then if user code do not break the loop then break on next iter() call.

No idea how this is compatible with current design.

**Comment by swanandx** [comment]
> break on next iter() call

I don't think that's possible. Iterator will always return something, usually it's `Some(_)` if something is there otherwise it keeps returning `None`. 
In our case, as we use `Result`, it will always return either `Ok(_)` or `Err(_)`. 
The user is responsible for (/not) polling the eventloop!

If you see the example, we explicitly `break` if we get error, otherwise u will keep calling next on iter and it will keep returning Err. 

For Disconnect, we have to do the same, like the example provided in my previous comment.

**Comment by BlackZork** [comment]
Ok, that's even better to signal worker thread about a disconnect. You could add it to [README](https://github.com/bytebeamio/rumqtt/blob/main/rumqttc/README.md#a-simple-synchronous-publish-and-subscribe).

The important thing is to stop processing incoming events, because there will be errors when worker loop try to publish something when processing those Incoming events while client is disconnecting.

**Comment by BlackZork** [comment]
I've updated to 0.24 and I see no changes. I still got `Notification = Err(MqttState(Io(Custom { kind: ConnectionAborted, error: "connection closed by peer" })))` after `client.disconnect()`.

**Comment by swanandx** [comment]
Hey @BlackZork , I closed the issue because it isn't possible to break from within the iter as explained here: https://github.com/bytebeamio/rumqtt/issues/662#issuecomment-1646670732

you can `break` in seeing outgoing disconnect message as discussed earlier.

**Comment by BlackZork** [comment]
I do not like thread:sleep workaround, I finally used shared variable to communicate with mqtt loop thread

I am attaching a modified version of your minimal example (untested, may not compile)

```rust
use rumqttc::{self, Client, MqttOptions};
use std::thread;
use std::time::Duration;

fn main() {
    let mqttoptions = MqttOptions::new("issue-662", "localhost", 1883);

    let exit_request = Arc::new(AtomicBool::new(false));
    let thread_exit_request = exit_request.clone();

    let (client, mut connection) = Client::new(mqttoptions, 10);
    thread::spawn(move || do_work(client));

    for (i, notification) in connection.iter().enumerate() {
        match notification {
            Ok(notif) => {
                println!("{i}. Notification = {notif:?}");
            }
            Err(error) => {
                if thread_exit_request.load(Ordering::Relaxed) == true {
                    println!("Exiting from MQTT loop after thread_exit_request");
                    break; 
                } else {
                    println!("Connection error, reconnecting");
                    thread.sleep(5);
                }
            }
        }
    }

    println!("Done with the stream!!");
}

fn do_work(mut client: Client) {
    thread::sleep(Duration::from_secs(1));
    exit_request.store(true, Ordering::Relaxed);
    client.disconnect().unwrap();
}
```
