### ISSUE TITLE
Client ID should be optional

### ISSUE THREAD

**Issue by andrewbaxter** [bytebeamio/rumqtt#667]
# Expected Behavior

When creating a client, using an empty client ID should work.

Per the 3.1.1 spec http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html

```
A Server MAY allow a Client to supply a ClientId that has a length of zero bytes, however if it does so the Server MUST treat this as a special case and assign a unique ClientId to that Client. It MUST then process the CONNECT packet as if the Client had provided that unique ClientId [MQTT-3.1.3-6].
```

# Current Behavior

Using an empty client id for the rumqttc client options results in a panic.

```
        let id = id.into();
        if id.starts_with(' ') || id.is_empty() {
            panic!("Invalid client id");
        }
```

**Comment by swanandx** [comment]
Hey, currently rumqttd doesn't generate random client ids, and will disconnect the clients without id. I think that's why we panic in rumqttc itself so user will know why it disconnected!

It is in plan to implement this, but as this is optional behaviour, it's on low priority 😅

**Comment by andrewbaxter** [comment]
This affects interaction with other (non rumqttd) servers.  Is rumqttc supposed to only be used with rumqttd?

Handling empty client ids is optional on the server, but supporting sending empty client ids is not optional for the client to be spec compliant.

**Comment by swanandx** [comment]
> Is rumqttc supposed to only be used with rumqttd?

Nope. You are correct about it, we should fix it if it's not per specs 😅
