### ISSUE TITLE
Current design and notes for high level client

### ISSUE THREAD

**Issue by tekjar** [bytebeamio/rumqtt#68]
I'll use this issue to articulate my thoughts around current design and how the high level client should look like to make the most out of the client with little effort. This issue won't be closed

The current async API looks like this

```rust
let (requests_tx, requests_rx) = channel(10);
let mut eventloop = eventloop(mqttoptions, requests_rx);

// connect and poll
let mut stream = eventloop.connect().await.unwrap();
while let Some(item) = stream.next().await {
    println!("Received = {:?}", item);
}
```

This pattern offers a lot of flexibility 

**`eventloop()` takes request `Stream`**

Stream being a trait allows library to not make any assumptions about request pattern. E.g
- streams can be both bounded and unbounded
- plug in a disk backed `Stream` for robustness across reboots
- attach a stream which `select!`s internally to tackle request priorities

**`connect` returns a `Stream`**

This stream does everything MQTT. A poll on this stream will do the following internally
- Take user request, handle state w.r.t this user request, create bytes and put it on network
- Ping based on incoming and outgoing activity. Make sure that the broker doesn't disconnect 
- Supervision to detect half-open connections and disconnect
- Flow control based on in-flight messages to not blowup ram usage (very much possible during slow incoming acks and time between half-open detection)
- Read incoming packet and respond back to the broker
- Yield incoming packets to the user

NOTE: These are necessary for a robust, persistent mqtt connection. I've seen a lot of implementations ignoring these only to get bitten at some point of time. Even if you are using different clients from other languages, keep these in mind

Now this `Stream` can be plugged into async/sync code as they see fit

**state separated from user `Stream`**

But the important thing here is that mqtt state is separated from the stream. It takes state as a reference. This allows users to freely create and destroy connections and resume from where we left. This makes reconnections simple. Just wrap the above code in a loop

```rust
loop {
    let mut stream = eventloop.connect().await.unwrap();
    while let Some(item) = stream.next().await {
        println!("Received = {:?}", item);
    }
}
```

Again, how client should reconnect (10 times or infinite) is left to the user.

**high level client**

All these features are great if you've sophisticated uses but not every one has to understand all the details when they start. They can reach this stage of customization eventually. When they do, the solution is with in the reach.

Getting started with the library should be fun and easy. They don't have to know that they should poll the eventloop `Stream` with tokio, read about async rust or why there are 3 (and not 1) steps to start the eventloop

**rough sketch of client APIs**

This spawns a background thread where eventloop runs. `tx` is used send mqtt requests and `rx` is
used to receive notifications. Just like a channel

```rust
let (tx, rx) = rumq_client::spawn_eventloop(options)
```

And this if eventloop should run on current thread

```rust
let eventloop = rumq_client::eventloop(options);
let (tx, rx) = eventloop.handles();
eventloop.run()
```

**Comment by qm3ster** [comment]
So in the high-level example eventloop takes over one thread, and nothing else can ever run there?
Do you feel this is an adequate compromise?
Maybe there should be a builder where you add "callbacks", and then you finally "run" the client (with the callbacks executing on this thread)?

**Comment by tekjar** [comment]
> So in the high-level example eventloop takes over one thread, and nothing else can ever run there?

Yeah

> Do you feel this is an adequate compromise?

I think it's a necessary compromise to make things as easy as possible. Are talking about under utilization of this thread? I'm assuming OS is smart enough and the cost of this extra thread is too trivial to care about. Is there any advantage to running eventloop code and user code on the same thread? (other than a minor cost). This is also a footgun when callback code is too expensive and eventloop halts causing a broker disconnection.

Callbacks in rust gives a lot of trouble to a lot of people because of closure rules. Given ease of use is on of the goal, this would be an anti pattern

Also back pressure is difficult with callbacks

**Comment by thburghout** [comment]
Would it be possible to add a `iter_for(duration: Duration)` to the synchronous connection API? That way various other tasks can be polled periodically as is common in synchronous single threaded programs.

Let me know if you would like me to create a separate issue for this. At this stage it seemed more applicable in the high level design discussion.
