### ISSUE TITLE
Synchronous client.subscribe hangs after ~10 subscriptions if connection.iter().enumerate() is not called

### ISSUE THREAD

**Issue by BlackZork** [bytebeamio/rumqtt#692]
# Expected Behavior

I should be able to call client.subscribe() as many times as I like without entering main loop [in this example from docs](https://github.com/bytebeamio/rumqtt/tree/main/rumqttc#a-simple-synchronous-publish-and-subscribe).

# Current Behavior

If you call `client.subscribe("hello/rumqtt", QoS::AtMostOnce).unwrap();` multiple times (>10 in my case) before entering main loop then thread is stuck in client.subscribe forever

# Workaround:

```rust
pub fn subscribe(&self, topic: &str, client: &mut Client, connection: &mut Connection) {
      client.subscribe(topic, QoS::AtLeastOnce).unwrap();
      // without loop subscribe hangs after 10 calls to client.subscribe()
      for (_i, notification) in connection.iter().enumerate() {
          match notification {
              Ok(event) => {
                  if let Event::Outgoing(_evt) = event {  //yes, I should check _evt type here....
                      debug!("Subscribed to {:?} ", topic);
                      break;
                  }
              },
              Err(_) => { break; } //errors ignored for simplicity, should be handled in real life scenario
          }
      }
}
```

## Context

* Operating System: Arch linux
* Toolchain version:  cargo 1.70.0 (ec8a8a0ca 2023-04-25)
* rumqttc = "0.17.0"

**Comment by BlackZork** [comment]
Unfortunately I do not know number of subscriptions in advance. I think queue size should be managed internally, not in user code.

**Comment by swanandx** [comment]
as per current design, to make any _progress_ you must poll the eventloop, until then we can buffer some requests in channel, but it's bounded as mentioned by @Nickztar .

Unbounded clients would be great to have, there is also a open issue for it #658 . 

We want to tackle / introduce unbounded clients while adding builder pattern ( that way we won't be breaking API multiple times for low impact change ).

**Comment by BlackZork** [comment]
Ok, so maybe it is better to add a helper function like my workaround and update docs, because if one follows official example it may end in this bug that is very hard to detect before code is run in production.

**Comment by swanandx** [comment]
>  so maybe it is better to add a helper function 

Can you elaborate more? Didn't get it 😅

btw, you can also spawn a separate thread for polling eventloop ( similar to example in rumqttc README ). That way you will make progress as well as won't block.

**Comment by BlackZork** [comment]
Thanks for hint. I already have main event loop in separate thread. It is a chicken-egg problem: I need initial subscriptions to run main loop, and main loop is needed to send initial subscriptions.

I resolved it by moving initialization code that does client.subscribe() after main loop is started. I have to guard more structures with std::sync::Arc for this to work.

You may see [this diff](https://github.com/BlackZork/mqtt-light-switch/commit/502ffb2256a90c5177e25e7cc1586ec76ed6b1dc) to [this file](https://github.com/BlackZork/mqtt-light-switch/blob/main/src/main.rs#L100) for details if you have spare time :-)

Anyway, I have a working solution so I am closing this issue. Thanks for your time!
