### ISSUE TITLE
Wrong README installation command for rumqttc

### ISSUE THREAD

**Issue by igiona** [bytebeamio/rumqtt#718]
# Expected Behavior

The rumqttc installation documentation (https://github.com/bytebeamio/rumqtt/blob/main/README.md) states a valid cargo command and explains the various rust-features of the crate.

# Current Behavior

```bash
$ cargo add rumqttc --all-features
error: unexpected argument '--all-features' found

  tip: a similar argument exists: '--features'

Usage: cargo add [OPTIONS] <DEP>[@<VERSION>] ...
       cargo add [OPTIONS] --path <PATH> ...
       cargo add [OPTIONS] --git <URL> ...

For more information, try '--help'.
```

# Failure Information (for bugs)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows
* Toolchain version: cargo 1.72.0 (103a7ff2e 2023-08-15)

A good answer/explanation for the failure can be found here: https://users.rust-lang.org/t/cargo-insists-unexpected-argument-all-features-found/93404/3

**Comment by swanandx** [comment]
Hey, good catch! Thanks for reporting 😄 I removed the invalid `--all-features` flag from README
