### ISSUE TITLE
vulnerability in ws_stream_tungstenite > tungstenite-rs

### ISSUE THREAD

**Issue by Arend-Jan** [bytebeamio/rumqtt#721]
error: 1 vulnerability found!
Version:   0.19.0
Title:     Tungstenite allows remote attackers to cause a denial of service
Date:      2023-09-25
ID:        RUSTSEC-2023-0065
URL:       https://rustsec.org/advisories/RUSTSEC-2023-0065
Severity:  7.5 (high)
Solution:  Upgrade to >=0.20.1
Dependency tree:
tungstenite 0.[19](https://github.com/kpn-dsh/dsh/actions/runs/6395708440/job/17360103398#step:10:20).0
├── ws_stream_tungstenite 0.10.0
│   └── rumqttc 0.[22](https://github.com/kpn-dsh/dsh/actions/runs/6395708440/job/17360103398#step:10:23).0

at the moment of writing, there is no update of the ws_stream_tungstenite library jet, but it will follow https://github.com/najamelan/ws_stream_tungstenite/issues/13

**Comment by Arend-Jan** [comment]
Update of ws_stream_tungstenite, which does the step-up to the newest version of tungstenite has been released by @najamelan  

There are some breaking change https://github.com/najamelan/ws_stream_tungstenite/blob/0.11.0/CHANGELOG.md

**Comment by Arend-Jan** [comment]
I've created a pull request: https://github.com/bytebeamio/rumqtt/pull/728

**Comment by swanandx** [comment]
Thanks for the contribution and update regarding `ws_stream_tungstenite`! I will update the version in rumqttd as well.
