### ISSUE TITLE
rumqttc: Include clientId, username and password in the websocket requests

### ISSUE THREAD

**Issue by Vilayat-Ali** [bytebeamio/rumqtt#722]
# Expected Behavior
`rumqttc` should include `clientId`, `username` and `password` in the websocket requests. 

# Current Implementation
uses only broker address to contruct a connection

**Comment by de-sh** [comment]
Closing this as these are part of the Connect Packet, JWT based websocket level authentication should be addressed separately, but doesn't look like a concern atm since we already have support for websockets over TCP+TLS.
