### ISSUE TITLE
rumqttd: Configurable or "smart" RusTLS options.

### ISSUE THREAD

**Issue by nathansizemore** [bytebeamio/rumqtt#745]
# Expected Behavior

When setting up tls with rustls, the server private key should be able to be any valid private key.

# Current Behavior

When using rumqttd with rustls, the server private key only accepts RSA, but no call outs docs regarding this.

## Context

Let's Encrypt default `privkey1.pem` acme output isn't RSA. It's a lot of stepping though code because there isn't documentation stating this to figure out it was forced to be RSA here:

```rust
// Get private key
let key_file = File::open(key_path);
let key_file = key_file.map_err(|_| Error::ServerKeyNotFound(key_path.clone()))?;
let keys = rustls_pemfile::rsa_private_keys(&mut BufReader::new(key_file));
```

It should either be specified in the config on how to read the pem files, or try and be "smart" and iterate over more options than just RSA.

**Comment by swanandx** [comment]
This should be solved in #743 ! Please check the discussion there, thank you 💯

**Comment by nathansizemore** [comment]
No worries. It's the same thing basically, just for the broker end. :smiley_cat:

**Comment by swanandx** [comment]
> more options than just RSA.
>

Like? [rustls_pemfile](https://docs.rs/rustls-pemfile/latest/rustls_pemfile/#example-code) can read RSA, EC and PKCS8. Is there any other type?

**Comment by nathansizemore** [comment]
Ideally with rustls, it would cover all options they provide from their crates. So just those would be great. Native can do whatever native does.

**Comment by nathansizemore** [comment]
I can do a draft PR does tries over each and returns an error if all fail. Would that be acceptable "smartness" for acceptance?

**Comment by swanandx** [comment]
> Ideally with rustls, it would cover all options they provide from their crates. So just those would be great.
>

I didn't get wdym by using rustls to cover options, rustls [docs](https://docs.rs/rustls/latest/rustls/struct.Certificate.html) suggest using rustls_pemfile to parse the PEM files.

> I can do a draft PR that tries over each and returns an error if all fail.
>

Sure, it will be similar to PR mentioned above right? Just using `read_one()` to get the key.

PS: @henil do we want this in broker? I believe we should, wdyt?

**Comment by nathansizemore** [comment]
I just meant trying `ec_private_keys`, `pkcs8_private_keys`, and `rsa_private_keys` by all options they support, since they provide those with `rustls_pemfile`.

**Comment by swanandx** [comment]
> This should be solved in #743 ! Please check the discussion there, thank you 💯
> 
> update: above pr is for rumqttc, my bad, i thought you were mentioning rumqttc 😅 

Hey @nathansizemore , turns out PR 743 was actually for rumqttd, and I don't know what I saw back then to edit reply and say it was for rumqttc 😭

**Comment by AlexandreCassagne** [comment]
Hey both,

Perhaps after both these are merged, we can add a PR with an example/test of rumqttc and rumqttd working together with key pairs.

The rumqttd PR is ready (#743) but lacking tests

**Comment by swanandx** [comment]
Closing this issue as PR #743 is merged :tada: Thank you!
