### ISSUE TITLE
Wildcard passed as topic panics

### ISSUE THREAD

**Issue by Standaa** [bytebeamio/rumqtt#754]
# Expected Behavior
Hello, I am unsure whether this is a bug, but I expect being able to pass '#' as a topic to subscribe to all topics.

# Current Behavior
The app panicks with the following error:
`thread main panicked at called `Result::unwrap() on an Err value: MqttState(SubFail { reason: NotAuthorized })'`

## Context
I am building an MQTT to postgres bridge

* Operating System: MacOs M1
* Toolchain version: 
rustc 1.72.1
rumqttc = "0.23.0"

**Comment by swanandx** [comment]
This is not an bug. most likely the broker you are using disallows `#` subscriptions, and that is why it rejects with error that you aren't authorized to make `#` subscriptions.

Please check the docs of broker you are using to verify this! Feel free to reopen the issue if required, thank you!
