### ISSUE TITLE
async_std support?

### ISSUE THREAD

**Issue by holotrack** [bytebeamio/rumqtt#793]
Like in title. Is there possibility to use rumqttc with async_std instead of tokio?

**Comment by swanandx** [comment]
async_std is compatible with [tokio runtime](https://docs.rs/async-std/latest/async_std/#features), so i think it should work? or is it other way around?

btw, what are the benefits of using async_std? we currently don't have option for users to choose between runtime, but this will really be cool feature to have!

we can have features like `tokio-runtime` ( default ) & `async-std-runtime` to let user choose the runtime. ( and in future `embassy-runtime` as well :rocket: )

would you like to contribute to this?

thanks :)

**Comment by holotrack** [comment]
@swanandx
"async_std is compatible with [tokio runtime](https://docs.rs/async-std/latest/async_std/#features), so i think it should work? or is it other way around?"

I tried to use it with asycn_std instead of tokio, so i change a little bit [async example](https://github.com/bytebeamio/rumqtt/blob/main/rumqttc/examples/asyncpubsub_v5.rs)" to:

```
use async_std::task;
use rumqttc::v5::mqttbytes::QoS;
use rumqttc::v5::{AsyncClient, MqttOptions};
use std::error::Error;
use std::time::Duration;

#[async_std::main]
async fn main() {
    pretty_env_logger::init();
    // color_backtrace::install();

    let mut mqttoptions = MqttOptions::new("test-1", "localhost", 1884);
    mqttoptions.set_keep_alive(Duration::from_secs(5));

    let (client, mut eventloop) = AsyncClient::new(mqttoptions, 10);
    task::spawn(async move {
        requests(client).await;
        task::sleep(Duration::from_secs(3)).await;
    });

    loop {
        let event = eventloop.poll().await;
        match &event {
            Ok(v) => {
                println!("Event = {v:?}");
            }
            Err(e) => {
                println!("Error = {e:?}");
                return ();
            }
        }
    }
}

async fn requests(client: AsyncClient) {
    client
        .subscribe("hello/world", QoS::AtMostOnce)
        .await
        .unwrap();

    for i in 1..=10 {
        client
            .publish("hello/world", QoS::ExactlyOnce, false, vec![1; i])
            .await
            .unwrap();

        task::sleep(Duration::from_secs(1)).await;
    }

    task::sleep(Duration::from_secs(120)).await;
}
```

And its compiling but im getting such error:

```
    Finished dev [unoptimized + debuginfo] target(s) in 5.74s
     Running `target/x86_64-unknown-linux-gnu/debug/of-controller`
thread 'main' panicked at /home/holo/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rumqttc-0.23.0/src/v5/eventloop.rs:131:38:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So i assumed there are some dipper dependencies on tokio than just changing runtime in `main` code.

"we can have features like tokio-runtime ( default ) & async-std-runtime to let user choose the runtime. ( and in future embassy-runtime as well 🚀 )"

I would be really happy to see it working, because im making my Rust learning project with emabssy-rs on RP Pico W for my sensors where i have problem to choose no_std MQTT library too. So would be nice to have on each environment same solution.

 I choose async_std over Tokio because in my controller for sensors i want to use capnproto which are supporting async_std and i just dont want to mix runtime environments. I can not answere what are benefits of async_std over Tokio becasue i just started learning Rust about month ago so i just don tknow. I just decided to stick with native Rust libs as much as possible for this project and avoid using of Tokio ecosystem.
 
 "would you like to contribute to this?"
 
 Like mentioned above i just started learning Rust moth ago, and basically programing to (before i had only basic knowledge  and limited experience with C and Go). This is my first learning project,  so my knowledge for sure is not enough to handle such task.

**Comment by swanandx** [comment]
you have to enable the `tokio1` features in `Cargo.toml`! e.g.

```toml
async-std = { version = "1.12.0", features=["attributes", "tokio1"]}
```

then the example would work :)

**Comment by swanandx** [comment]
> because im making my Rust learning project with emabssy-rs on RP Pico W for my sensors where i have problem to choose no_std MQTT library too
>

embassy in really cool! 

> I just decided to stick with native Rust libs as much as possible for this project and avoid using of Tokio ecosystem.
>
I don't think `async-std` can be considered native Rust lib? btw, Tokio ecosystem is huge, like lots of user, who want an battle tested async runtime choose tokio! ( ofc other runtimes like smol, embassy, async-std are cool and have their own purpose haha )

> Like mentioned above i just started learning Rust moth ago, and basically programing to (before i had only basic knowledge and limited experience with C and Go). This is my first learning project, so my knowledge for sure is not enough to handle such task.
>

no worries! thanks :rocket:

**Comment by holotrack** [comment]
> > And its compiling but im getting such error:
> 
> @holotrack you have to enable the `tokio1` features in `Cargo.toml`! e.g.
> 
> ```toml
> async-std = { version = "1.12.0", features=["attributes", "tokio1"]}
> ```
> 
> then the example would work :)

its working, thank you :)

>I don't think async-std can be considered native Rust lib? btw, Tokio ecosystem is huge, like lots of user, who want an battle tested async runtime choose tokio! ( ofc other runtimes like smol, embassy, async-std are cool and have their own purpose haha )

I think for my needs i think async_std will be better siuted (usage of capnproto, embassy-rs, egui). Im happy i can go further with rumqttc instead of Paho as it was only one which support async_std. Hope there will be "Clean" version for rumqttc too in future and cant wait no_std support :)
