### ISSUE TITLE
An Error = MqttState(AwaitPingResp) error occurred when creating a connection using rumqttc v5

### ISSUE THREAD

**Issue by zmjssm** [bytebeamio/rumqtt#801]
![image](https://github.com/bytebeamio/rumqtt/assets/153150249/35fa8435-ed9b-4bbd-ad6d-7126f4bcf019)

**Comment by zmjssm** [comment]
I didn't have this problem with version 0.22.0 before

**Comment by swanandx** [comment]
Hey @zmjssm , which broker are you using? this might be issue related to broker and not rumqttc.

I tried with rumqttd, and latest main branch ( and also the 0.23.0 ) version seems to work fine with the code you provided. I wasn't able to reproduce it.

the AwaitPingResp gets triggered when there are previously pending ping request and we try to ping again.

In logs provided in your screenshot, you can see an `Outgoing(PingReq)`, but broker never responded back with anything, as the keepalive time passed ( 100s passed without receiving anything in this case ), rumqttc tried to send ping but saw the previously pending request, and hence generated the error.

lmk if that makes sense, thank you!

**Comment by swanandx** [comment]
i will be closing the issue, feel free to reopen it if required :)
