### ISSUE TITLE
rumqttc: Could publish/subscribe methods directly return the msg id?

### ISSUE THREAD

**Issue by t-moe** [bytebeamio/rumqtt#843]
I have an application where multiple parts of the app send/receive messages concurrently (async). A worker thread polls the eventloop and sends the incoming publications/subacks/pubacks to the individual parts of the application.

It would be nice if the publish/subscribe/unsubscribe methods could directly return a message id (publish: only for QoS > 0)  without having to poll the eventloop first. This way the individual parts can remember the message id of the message they just tried to publish, and later they when an incoming puback message appears on the eventloop, continue with the business logic. Currently this is all a bit more involved, because the individual parts of the app first need to somehow figure out the msgid of the publication they just sent. Unfortunately the individual parts cant just wait on the next Outgoing Event, because that could be triggered by another part of the application.

I'm aware that this is a rather big change and we would have to access the state inside the client, but I wanted to get your opinions on the topic nonetheless...

**Comment by dlips** [comment]
Hi @t-moe, you are not the only one needing this functionality, see:
* https://github.com/bytebeamio/rumqtt/issues/805
* https://github.com/bytebeamio/rumqtt/issues/349
As far as I know, the feature is being worked on (I am only a user following the discussions in the issues, no maintainer)

**Comment by t-moe** [comment]
Ooops.
Closing this as dup.

Thank you.
