### ISSUE TITLE
Does `MqttOptions` `request_channel_capacity` field do anything?

### ISSUE THREAD

**Issue by cartertinney** [bytebeamio/rumqtt#844]
As far as I can tell, the `request_channel_capacity` field of the `MqttOptions` struct doesn't do anything. Perhaps I'm missing something, but it seems like the actual channel capacity is set when you instantiate an `AsyncClient` with the `cap` parameter. Looking into the source code, I see nowhere that `request_channel_capacity` is actually used. Is this a deprecated field? Or am I just missing it's functionality?

**Comment by swanandx** [comment]
Actually, as refactoring of APIs / MqttOptions was going on, I was thinking we can use that `request_channel_capacity` instead of `cap`.

So didn't deprecate it 😅 feel free to let us know your thoughts!

Thanks!

**Comment by cartertinney** [comment]
@swanandx That seems like a better place for it, especially if you end up making unbounded channels an option, as I've seen some discussion on.

But to be clear, right now, does this field do anything?

**Comment by swanandx** [comment]
currently `request_channel_capacity` this doesn't do anything. It will just be ignored
