### ISSUE TITLE
rumqttc: change connection options after creating client instance

### ISSUE THREAD

**Issue by xiaocq2001** [bytebeamio/rumqtt#886]
# Expected Behavior

We do not appear to currently have a way to connect with clean_session = True on the initial connect, and then change to using clean_start = False on successive reconnects (i.e. we want to start a clean session, and then if the connection is lost, try and re-establish the same session). 

# Current Behavior

The options are saved in EventLoop instance, there is no way to modify it after the client and event loop is created. Re-connection uses the options in EventLoop and there is no way to modify them.

**Comment by memark** [comment]
Does that solve your issue @xiaocq2001?

**Comment by xiaocq2001** [comment]
@memark yes.

**Comment by memark** [comment]
@xiaocq2001 Great! Please close this issue then.
