### ISSUE TITLE
Unable to connect to Broker

### ISSUE THREAD

**Issue by suncunxudsb** [bytebeamio/rumqtt#888]
Execute the following command on Centos to install rumqttd； 
“cargo install --git https://github.com/bytebeamio/rumqtt rumqttd”
This is a screenshot of the operation:
![1720494853346](https://github.com/bytebeamio/rumqtt/assets/129515418/c672c6eb-74de-414c-ba87-bcf45f0785fe)
This is the content of the configuration file:
`id = 0

[router]
id = 0
max_connections = 10010
max_outgoing_packet_count = 200
max_segment_size = 104857600
max_segment_count = 10

[v4.1]
name = "v4-1"
listen = "0.0.0.0:8848"
next_connection_delay_ms = 1
    [v4.1.connections]
    connection_timeout_ms = 60000
    max_payload_size = 20480
    max_inflight_count = 100
    dynamic_filters = true

[v5.1]
name = "v5-1"
listen = "0.0.0.0:1884"
next_connection_delay_ms = 1
    [v5.1.connections]
    connection_timeout_ms = 60000
    max_payload_size = 20480
    max_inflight_count = 100

[prometheus]
listen = "127.0.0.1:9042"
interval = 1
[ws.1]
name = "ws-1"
listen = "0.0.0.0:8083"
next_connection_delay_ms = 1
    [ws.1.connections]
    connection_timeout_ms = 60000
    max_client_id_len = 256
    throttle_delay_ms = 0
    max_payload_size = 20480
    max_inflight_count = 500
    max_inflight_size = 1024

[console]
listen = "0.0.0.0:3030"
`
This is a screenshot of the client code。Consistent with the example code, I only modified the IP address。
![1720495007953](https://github.com/bytebeamio/rumqtt/assets/129515418/ab4481d2-02ef-4552-9066-4ba1e21fbd97)

I'm sure the port number is open ,but I can't connect to the broker。

This is a screenshot of the program running:
![1720495501581](https://github.com/bytebeamio/rumqtt/assets/129515418/1978b967-8158-43db-afdf-df3b9ef792f0)

**Comment by swanandx** [comment]
can you verify if you can actually reach that IP address or not?

**Comment by suncunxudsb** [comment]
> can you verify if you can actually reach that IP address or not?

yes
![1720503573465](https://github.com/bytebeamio/rumqtt/assets/129515418/b0b3c725-5e15-4a61-b8eb-82f998caaa33)

**Comment by suncunxudsb** [comment]
> can you verify if you can actually reach that IP address or not?
My server is unable to open port numbers. I successfully switched to another server。 Thank You。
