### ISSUE TITLE
rumqttd: how to get the source ip for mqtt forward?

### ISSUE THREAD

**Issue by thomas725** [bytebeamio/rumqtt#891]
I'd like to get the source ip (+port) of who sent an mqtt topic change, is that available through the forward struct? Or is there some other way I'd need to subscribe to updates than this:
https://gitlab.com/thomas351/rust-influxdb-udp-logger/-/blob/main/src/mqtt_relay.rs#L45

This is no bug report, just a question how to use your library, I hope it's okey to post this as an issue entry here. If there's some other preferred channel for asking questions please point me to it.

I'm debating with myself weather I should ditch the library usage and just open a TCP listener for the 1883 MQTT port myself, but I have no idea of how complex the protocol is (and am not too keen to find out ;)) - though that would save me a few MB of binary size and would make it trivial to get source ip & port.

**Comment by swanandx** [comment]
> is that available through the forward struct? 
>
Nope. IP+port is not there. In MQTT, subscribers don't know information about the publishers ( & vice versa ).

If you wish, you can either:
- make specific topic structure to identify publisher, like /:id/hello so device 1 will publish to /1/hello, 2 to /2/hello and so on
- if you are using MQTTv5, you can add the information as user properties
- add the info in payload on packet

**Comment by thomas725** [comment]
thanks for the reply. I'm only using MQTT to integrate some old "legacy" devices I can't (or don't want to) modify anymore into my current smart home setup, so I can't modify the topics / payload.

For now I'll live with the fact that I can't tell the source of those metrics, and if it bugs me more than now sometime in the future I'll maybe try to implement a more naive mqtt server that just processes the topic update packages directly.

But big thanks for the reply and for maintaining this library :)

**Comment by swanandx** [comment]
Incase you want to modify rumqttd to do so, [here](https://github.com/bytebeamio/rumqtt/blob/db1f261dd5cd6c69bbfd1058ba69ea8ef5f4fc38/rumqttd/src/server/broker.rs#L395) you are getting the  `addr` ( which will be socket address ), for now we just log it. You can get IP from there.

you can pass it to `remote` fn ( and then to router, via modifying connect packet or directly ).
But this won't still be there in `Forwards` ig, you might need to modify all incoming packets to have that info ( depends on your use case ).
