### ISSUE TITLE
Reconnection Issues with session

### ISSUE THREAD

**Issue by newcomertv** [bytebeamio/rumqtt#902]
# Expected Behavior

When shutting down and reconnecting to the same Broker later the peer should allow the connection

# Current Behavior

Sometimes using the mosquitto broker if the client program stop unexpectedly and later attempts to reconnect the connection is refused by the peer.

# Failure Information (for bugs)

Probably not a bug, if its a config issue though it would be nice to document that for new users.

By changing the client_id this issue is fixed.

Checking running processes the previous process does not exist.

Restarting the docker of the broker without removing persistent storage does not fix the issue.

## Context

This issue has been reproduced running both on Windows and Ubuntu 22.04 LTS.
Across a list of the latest rustc versions.

The issue is intermittent and thus hard to reproduce.

I'm guessing there is a sane default on one of the two sides somehow keeping some kind of session or the sort which doesn't exist when creating the new process.

client connect code:
```rust
        /// Buffer capacity for the rumqttc client (10 messages)
        const CAPACITY: usize = 10;

        let l_url = format!("{}?client_id={}", p_config.broker, p_config.client_id);

        let Ok(mut l_mqttoptions) = MqttOptions::parse_url(&l_url) else {
            error!("Unable to parse URL : {:?}", l_url);
            return Err(());
        };

        l_mqttoptions.set_keep_alive(Self::TIMEOUT);

        if !p_config.username.is_empty() && !p_config.password.is_empty() {
            l_mqttoptions.set_credentials(&p_config.username, &p_config.password);
            info!("Setting username / password credentials");
        }

        log::warn!(
            "Clean session was set to: {:?}, override to false",
            l_mqttoptions.clean_session()
        );
        l_mqttoptions.set_clean_session(false);

        let (l_client, l_connection) = rumqttc::Client::new(l_mqttoptions, CAPACITY);
        self.client = Some(l_client);
 ```

## Failure Logs
None :(

**Comment by swanandx** [comment]
on stopping the client process, mosquitto broker might be thinking it's still connected ( can be due to half open connections or something ) and might not allow connection with same client id again ( cuz as per it's state, that already exists ).

Not sure about the behaviour/working of mosquitto broker.

If you don't want to persist session, set the clean_session to true or you can decrease the keep alive interval and make sure that it's passed before reconnecting ( just an hack to get over half open connections ).

Closing this issue as it's not related to rumqtt, please feel free to comment/re-open if i missed something.

Thank you!

**Comment by swanandx** [comment]
wdym by anonymous connections / client_id?

**Comment by swanandx** [comment]
> Fingers crossed that rust to production works out in two weeks :sweat:
> 
All the best! It will work 🦀

BTW, we use rumqtt ( + wrapper around it to do some processing ) and Rust in production at Bytebeam ;)

> I ended up convincing the move to rust partially thanks to rumqtt actually :muscle: we used to use paho and C++.
>

That's really awesome to hear! <3 Would love to know more about your use case if you are okie to share :)

**Comment by tekjar** [comment]
> We're running a bunch of servers locally on site for a fully automated parking installation with charging capabilities.

That's a very interesting usecase @newcomertv. We'd love to follow along your journey and see if there are possible collaboration opportunities

Here's my email for your business team: raviteja@bytebeam.io
